### ISSUE TITLE
Timeseries Changed Rows 저장 방식에서 지원 중단된 인스턴스 처리

### ISSUE THREAD

**Issue by james-sungjae-lee** [ddps-lab/spotlake#119]
Timeseries Changed Rows 저장 방식은 t 시점을 기준으로 t+1 시점에 데이터가 변화하지 않았다면 t+1 시점의 데이터를 저장하지 않고, 데이터가 변화하였다면 t+1 저장하는 방법입니다.

Spot Price 를 포함한 Score 정보들에 대해서 이 방법을 적용할 때, 치명적인 문제점이 있을 수 있다는 점을 파악했습니다. 특정 워크로드(Instance-Region-AZ)가 t+1 시점에서 더이상 지원되지 않는 경우(지원 중단), 데이터베이스는 t 시점의 데이터만 가지고 있을 것입니다. 실제로는 t+1 시점에서 워크로드가 존재하지 않지만, t 시점 이후로 데이터 저장이 없기 때문에 t+1 시점에서는 데이터가 변화하지 않아 저장이 이루어지지 않았다고 잘못 이해될 수 있습니다.

이를 해결하기 위해서는 t+1 시점에서 특정 워크로드가 더 이상 지원되지 않는 경우, flag 를 표시하여야 합니다. 그래야만 실제 Query 시에 flag 를 기준으로 정확한 데이터 Query 를 수행할 수 있습니다. 이 문제는 이전에 개발하였던 Compare 모듈, Migration 이슈와도 깊게 관련이 있으며, 꼭 해결해야만 할 것으로 보입니다.

**Comment by chris0765** [comment]
#176 완성을 통해 해결될 이슈이므로 해당 이슈는 close하고, #176 이슈 완료 후 프론트엔드 작업이 필요한 건에 대해서는 새롭게 이슈를 만들어 다루도록 하겠습니다.
