### ISSUE TITLE
SpotLake 데모페이지의 Query 에서 InstanceType, Region, AZ 의 변화를 SelectBox 에 적용

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#137]

**Comment by chris0765** [comment]
@H0zzae @j-myeong 

AWS InstanceType-Region-AZ 페어 조합 json 파일
https://spotlake.s3.us-west-2.amazonaws.com/query-selector/query-selector-aws.json

Azure InstanceTier-InstanceType-Region 페어 조합 json 파일
https://spotlake.s3.us-west-2.amazonaws.com/query-selector/query-selector-azure.json

현재 사용하고 있는 latest 파일 대신 위의 파일들을 AWS, Azure의 select box에 사용하도록 해주시면 될 것 같습니다.

**Comment by chris0765** [comment]
현재 프론트엔드에서 latest.json파일을 계속 갱신하며 사용하는 것이 아닌, 하나의 정적 파일로 관리하고 있고, 그 형태가 query-selector.json 파일과는 달라 파일 형식을 변환해주는 과정을 필요로 하고 있습니다.

예)
latest.json, query-selector.json
[{"InstanceType":"r6gd.8xlarge","AZ":"aps1-az3","SpotPrice":0.4879,...},{"InstanceType":"r6gd.8xlarge",...},...]
association.json
[{"us-west-2": {"InstanceType": ["a1.2xlarge", "a1.4xlarge", "a1.large", ...], "AZ": ["usw2-az3", "usw2-az2", "usw2-az1", ...]}, ...]

데이터 수집/갱신 단계에서 파일 형식을 변환하기에는 적합하지 않을 것 같아, Lambda를 통해 변환된 형식으로 파일을 제공해드리고자 합니다.

**Comment by j-myeong** [comment]
AWS는 말씀해주신대로 되어있고,
Azure는 InstanceType: {region: [], InstanceTier: []} 로 되어있습니다.

따라서, 프론트엔드에서 처리하는 로직이 다른데 AWS와 동일한 형태로 처리가 가능하다면 로직을 동일하게 처리할 수 있을 듯 합니다.
@chris0765

**Comment by chris0765** [comment]
그러면 제가 생각하기에 InstanceType에 따라 region과 az, InstanceTier등이 바뀌도록 설정되어있으니 (region, az, instancetier에 all 선택),
azure의 형식을 바꾸기보다는 aws의 형식을 InstanceType:{Region,AZ}로 바꿀 수 있을까요?

**Comment by j-myeong** [comment]
넵, 그러면 확인해서 로직을 통일할 수 있을 것 같습니다!

**Comment by chris0765** [comment]
파일 링크입니다.

[association_aws.json]
https://spotlake.s3.us-west-2.amazonaws.com/query-selector/associated/association_aws.json

[association_azure.json]
https://spotlake.s3.us-west-2.amazonaws.com/query-selector/associated/association_azure.json

@j-myeong

**Comment by kmu-leeky** [comment]
다른 이슈에서 참조가 되었으니. 위의 aws, azure 의 associations 파일은 자동으로 업데이트가 되는거지? 그렇다면 이번에 gcp 도 같은 시나리오로 지원되게끔 하는게 좋겠다. 확인 후에 이 이슈는 close 하면 될듯 하다.

**Comment by red0sena** [comment]
AWS, Azure, GCP 모두 자동으로 association파일을 업데이트하므로 colse하겠습니다.
