### ISSUE TITLE
changed-row의 급격한 변화 시점 분석

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#164]
migration 도중, 2022-07-21 19:50:00부터 changed-row의 개수가 1000개 이상으로 증가하더니, 점진적으로 증가하여 3000대까지 증가한 후, 다시 점진적으로 감소하여 기존과 같이 200대를 유지하게끔 변화하는 데이터 구간이 존재하는 것을 발견하였습니다.

데이터가 급격히 증가하기 시작한 시점이 한국 시간으로 새벽 4시 50분이기 때문에, spotlake 시스템보다는 aws측에서의 문제일 가능성에 초점을 두고 있습니다.

**Comment by HeeNamgoong** [comment]
6월달부터 10월달까지의 특정기간동안 IF가 급격하게 변하는 지점이 있었습니다.
IF가 변화한 원인을 알기위해서 각 timestamp의 instancetype, AZ를 알아냅니다.
previous데이터와 current데이터를 비교하여 동일한 InstanceType, AZ, region을 분석하여 값이 변한 IF의  instancetype을 알아냅니다.
* 8/1 17:30 데이터
![image](https://user-images.githubusercontent.com/104904309/200182825-78fb0b01-63a7-4890-90db-fc0e43a018c1.png)
* 8/2 17:40 데이터
![image](https://user-images.githubusercontent.com/104904309/200182835-848fe28e-94a2-49cb-bbae-a37bfe5cfe4e.png)

만약 위에서 IF의 값이 변했다면 이때의 Instancetype이 변한 것입니다.

현재는 어떤식으로 코드를 작성할지 구상중에 있습니다.

**Comment by HeeNamgoong** [comment]
어떠한 Region의 어떤 AZ의 InstanceType들이 변했길래 IF가 많이 변화했는지 알아보기 위해서 먼저 8월달로 분석진행해 보았습니다. 분석 중, 한 가지 궁금한 점이 생겼습니다.


예를 들어, 8/16 17:40에서 변한 IF는 이전의 timestamp와 비교했을 때 676개 변했고 이전 timestamp에서는 IF가 0개 변했습니다.
그리고 어떠한 AZ와 Region을 가진 InstanceType이 변했길래 많은 IF가 변했는지 알아보고 있었는데 아무 InstanceType도 변하지 않았습니다. 
다시 말하면 전 데이터에서는 변하지 않았던 IF와 현재에서는 많이 변한 IF를 비교했을 때 676개가 변했다고는 하지만 실제 InstanceType들은 변하지 않고 모두 동일합니다.

하지만 반대로 8/8 21:30에서 변한 IF는 이전의 timestamp와 비교했을 때 7010개 변했고 이전 timestamp에서는 7032개가 변했습니다. 그리고 위의 경우와는 다르게 모든 InstanceType들이 변했습니다.

전자와 후자는 둘다 어쨌든 IF가 변한 값이 있는데 왜 전자는 변한 Instance가 없고 후자는 모든 instance들이 변했는지 잘모르겠습니다. 제가 코드를 잘못 짠 건지 아니면 IF가 많이 변해도 변하는 InstanceType들이 없을 수도 있는 건지 궁금합니다.

**Comment by kmu-leeky** [comment]
논문에서 따로 분석을 해야 할듯
