### ISSUE TITLE
쿼리 시 instancetype-region-az의 구성

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#176]
현재 SpotLake에서 쿼리를 진행하기 위해 instancetype-region-az 선택 시 고려해야 할 사항이 있음

* Changed-Row 방식으로 전환함에 따라, Ceased Row에 대한 정보가 추가됨
* 현재 instancetype-region-az에 선택자로 사용되는 요소는 latest data를 활용하지만, 해당 데이터에는 Ceased Data가 포함되어있지 않음
* Ceased Data 없이 최신에 지원하는 instancetype-region-az를 선택자로 제공해야할 것인지, 기존 데이터의 모든 선택자를 제공해야할 것인지에 대한 결정이 필요함

**Comment by kmu-leeky** [comment]
오케이. 재일아. 이전에 미뤄뒀던 부분의 일들도 하나씩 정리해보자. 이건 어떤 이슈를 다루는지 기억이 어렴풋이 나는듯 한데, 내일 같이 이야기를 나눠보자.

**Comment by chris0765** [comment]
2022-01-01부터의 데이터를 읽어오고 instancetype-region-az 데이터를 s3에 업로드 하는 코드 작성을 완료했습니다.
이후로는 다음과 같이 진행하겠습니다.

1. 작성된 코드가 정상적으로 동작하는지 테스트
2. 정상적으로 동작한다면 collector에 추가할 코드를 작성
3. 2번 코드가 정상적으로 작동하는지 테스트
4. 정상적으로 동작한다면 1번코드를 실행
5. 1번 코드의 기간을 조절해가며 코드 동작 완료 시간이 현재 시간을 따라잡을 때까지 반복 실행
6. 이후 collector에 2번 코드 적용

5번을 조금 자세히 서술하자면, 2022-01-01부터 현재까지의 데이터를 쿼리하고 처리하는데에는 많은 시간이 들기 때문에, AWS의 경우 다음 데이터 수집 주기인 10분 후까지 코드가 완료되지 않을 가능성이 높습니다.
때문에 코드 실행 시작 시점부터 코드 실행 완료 시점까지의 데이터에 대해 코드를 추가로 동작시킨 후, 코드 실행 완료 시간이 다음 수집 주기가 되기 이전까지 계속 반복합니다.
이후 collector에 기능을 추가해야합니다.

**Comment by kmu-leeky** [comment]
재일아. 이걸 그냥, Unique 한 인스턴스 타입만 얻어오는 sql 쿼리해도 괜찮지 않을까? 과거의 데이터에 대해서는 sql 쿼리로 unique 한 값을 얻어오고 그걸 가지고 association 파일을 하나 만들어두고, 그리고 나서 새로운 인스턴스들은 지속적으로 collector 에서 추가하는 방향으로. 내가 맞게 이해를 하고 있는건가?

**Comment by chris0765** [comment]
해당 이슈 알람을 확인하지를 못해서 교수님 코멘트를 지금 확인했습니다.
교수님께서 말씀햊주신것처럼, 과거부터의 데이터에 대해서는 unique하게 쿼리를 진행하면 compare 작업이 없어도 될 듯 합니다.

기존에 작성했던 코드의 테스트를 완료해두기는 하였는데, 실 적용때에는 교수님이 말씀해주신 방향으로 바꾸는 것이 괜찮아 보입니다.

변경하여 실제 적용을 마무리해보겠습니다.

**Comment by chris0765** [comment]
과거의 데이터에 대해 unique한 sql 쿼리를 사용하는 방법에 대해서:

* 2022-01-01 ~ 2023-02-14 까지의 데이터를 한번에 쿼리해야하다보니 너무 오랜 시간이 걸립니다.
* DISTINCT를 사용해 unique한 쿼리를 구현했는데, DISTINCT가 쿼리 시에 시간을 많이 잡아먹는 방법이라 합니다.
* 실제로 기존에 migration을 진행했던 인스턴스와 동일한 m5.2xlarge에서 해당 방법을 통해 시도해보았지만, 오랜 시간 쿼리가 계속되다가 Broken pipe가 발생하며 인스턴스와의 연결이 끊어졌습니다.
* 쿼리를 기다릴 시간과 더 좋은 인스턴스를 사용할 비용이 충분하다면 훨씬 더 구현하기 간단한 방법이 될 수 있습니다만, compare에 그리 큰 시간이 필요하지 않으므로 기존에 작성된 코드를 사용하는 것이 더 효율적으로 보입니다.

현재는 unique 쿼리가 아닌 기존 방식으로 데이터 쿼리를 모두 완료하였고, compare 작업 진행중에 있습니다.
compare 작업이 완료되면,
완성된 파일을 s3에 업로드 -> collector에 기능 추가 -> 첫 it-rg-az 페어 생성 기간의 종료 시점과 collector 수집 시작 시점 사이 기간에 대해 it-rg-az 페어 생성 작업
으로 완료될 예정입니다.

**Comment by chris0765** [comment]
데이터를 timestream에서 쿼리해올 때, 전체 기간에 대해 DISTINCT를 하는 것이 아니라 멀티프로세싱을 이용해 각각의 기간에 대해 DISTINCT를 사용한 쿼리를 통해 데이터를 받아오고 있습니다.

현재 쿼리는 완료되었고, 각각의 기간에 대해 compare 작업을 진행중인데,
한번 DISTINCT를 통해 걸러진 데이터들임에도 불구하고 26065514 row의 데이터를 받아왔습니다.
1차적인 InstanceType-Region-AZ 페어 완성까지는 어느정도 시간이 걸릴 것으로 예상됩니다.

**Comment by chris0765** [comment]
compare에 너무 오랜 시간이 걸려 해결 방법을 찾던 중,
전체 데이터를 하나의 데이터프레임에 저장해두고, 이를 각각의 시점끼리 compare 하는 과정의 반복으로 중복을 제거하기보다는, dataframe 자체의 중복 제거 기능을 이용하면 어떨까라는 생각을 하였고,
기존의 compare 작업을 삭제하고 dataframe의 drop_duplicate를 사용하여 중복을 제거하였습니다.

2022-01-01 ~ 2023-02-14 00:00:00 까지의 데이터들 중 InstanceType-Region-AZ의 조합은 총 24887개가 있습니다.
해당 데이터를 S3에 업로드 후, collector 기능 추가 작업을 진행하겠습니다.

**Comment by chris0765** [comment]
#394 PR을 통해 collector 기능까지 업데이트 되었습니다.
현재 collector에 적용 후 나머지 기간 업데이트도 끝내도록 하겠습니다.

**Comment by chris0765** [comment]
현 이슈 종료 후, gcp와 azure에 대해 각각 새로운 이슈를 오픈하도록 하겠습니다.
