### ISSUE TITLE
[GCP] metadata 동적 트래킹

### ISSUE THREAD

**Issue by wynter122** [ddps-lab/spotlake#190]
long term issue

**Comment by wynter122** [comment]
과거에 region 별 지원 인스턴스 타입 및 타입별 cpu, ram 정보등을 제공하는 API를 확인했고, 현재 과거에 기록한 코멘트들을 살펴보며 작업을 계획 중입니다.
https://github.com/ddps-lab/spotlake/issues/199#issuecomment-1280976134

자세히 정리해둔 내역이 있어서 계획을 수월하게 짤 수 있을 것 같습니다.
전체적으로 작업할 내용이 정해지면 다시 코멘트로 알려드리겠습니다.

**Comment by wynter122** [comment]
### 구현 시나리오 공유

노션을 통해 공유합니다.
https://road-freedom-b61.notion.site/GCP-metadata-02fcbf6a836d4398a56cbaa779604ac4

**Comment by wynter122** [comment]
### 구현 시나리오 공유

노션 링크 첨부하도록 하겠습니다.
https://road-freedom-b61.notion.site/GCP-metadata-02fcbf6a836d4398a56cbaa779604ac4

**Comment by kmu-leeky** [comment]
현영아. GCP 인스턴스 타입 동적으로 업데이트 하는 작업 업데이트 상황 공유해줄래?

**Comment by wynter122** [comment]
네 교수님. 
저번주부터 개인적인 일이 있어서 작업이 좀 늦어졌습니다. 이번 주 안으로 PR 올려도 괜찮을까요..?

**Comment by kmu-leeky** [comment]
응 현영아. 일 잘 보고 완성되면 같이 검토해보자. 꼭 이번주안에 안해도 괜찮으니 너무 서두르지는 말고.

**Comment by wynter122** [comment]
네 교수님, 우선 API 통해서 데이터 파싱 및 수집하는 모듈은 완성한 상황입니다.
다만, 기존 모듈에서 수집한 데이터로 대체하는 부분에서 시간이 좀 걸리는 것 같습니다.
우선 aggregated API 로 수집하여 metadata 화 시킨 데이터들을 공유드리는게 맞는 것 같아, 공유드린 후 마저 모듈 완성해보도록 하겠습니다

1. available region list
현재 기존에 크롤링하여 사용하던 vm instance 페이지에서, N/A 정보를 수집하여 필터링하고 있습니다.
다만, 이런 방법은 페이지 포맷이 변경되면 언젠가 또 수정이 이뤄져야 하므로 개선이 필요했습니다.
aggregated API 에서 zone 별 지원가능한 instance 의 metadata 형태로 output을 제공하는점을 사용하여 해당 부분을 개선하려는 시도를 하고 있습니다.
현재까지 데이터 파싱하여 region 별 지원가능 인스턴스 리스트를 확보해 둔 상태입니다.
(api 에서는 zone 까지 나누어 제공하지만, 이전에 zone 별 가격차이가 전혀 없다는 점을 파악하여 region 으로 파싱하고 있습니다.)
=> 위 데이터를 사용하여 vm instance 페이지 크롤링을 사용한 get_available_region 모듈을 대체할 예정입니다.
 
2. instance spec metadata
API 에서 제공하는 cpu, ram 의 정보로 인스턴스별 spec metadata 를 확보했습니다.

![image](https://github.com/ddps-lab/spotlake/assets/72314987/fc74bf61-b45f-44d4-acb6-9cf753827abc)

=> 기존에 gcp_metadata.py 에 하드코딩했던 정보들을 대체, 새로 추가된 인스턴스도 API 정보를 통해 반영이 가능하도록 사용할 예정입니다.

두 json 파일을 압축해서 공유드립니다.
[아카이브.zip](https://github.com/ddps-lab/spotlake/files/11449197/default.zip)
