### ISSUE TITLE
aws, azure, gcp 에서 제공되는 인스턴스의 사양을 수집해서 저장하는 기능 구현

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#199]
다양한 벤더에서 제공되는 인스턴스의 특성 비교를 위해서는 각 인스턴스의 세부 사양 정보가 필요함.
각 벤더별 인스턴스를 특징 지을수 있는 사양을 정리하고, 해당 정보를 수집해오는 모듈의 추가 구현이 필요함.
우선 각 벤더별로 인스턴스 정보를 얻어오는 모듈의 구현 및 가능성 확인 필요.

**Comment by wynter122** [comment]
본 이슈에서 각 벤더별 데이터 수집 가능성을 조사하였고, 세부 구현은 벤더별로 진행하고있기 때문에 close 합니다.
