### ISSUE TITLE
aws, azure, gcp 합동 쿼리 api 연동

### ISSUE THREAD

**Issue by H0zzae** [ddps-lab/spotlake#211]
https://ohu7b2tglrqpl7qlogbu7pduq40flbgg.lambda-url.us-west-2.on.aws/
해당 api를 통해 aws, azure, gcp 합동 쿼리 api 연동 작업 진행 중입니다. 
쿼리 연동 예시는 아래와 같습니다. 
![image](https://user-images.githubusercontent.com/39540561/192264080-a3988720-514c-40fe-ae22-a27f239bd57c.png)

**Comment by red0sena** [comment]
현재 azure도 정상적으로 timestream에 데이터가 업로드 되고 있습니다. 
그러나 아직 쿼리가 정상적으로 되지 않는것 같습니다.

<img width="600" alt="Screen Shot 2022-11-11 at 4 19 52 PM" src="https://user-images.githubusercontent.com/106056971/201287512-dc37a185-e99f-4cda-a432-1e96ca83cb57.png">

@H0zzae , @j-myeong  관련작업 공유 부탁드립니다!

**Comment by kmu-leeky** [comment]
완료된듯.
