### ISSUE TITLE
AWS 인스턴스별 하드웨어 특성 수집 모듈 구현

### ISSUE THREAD

**Issue by HyeonYoung-Lee** [ddps-lab/spotlake#238]
본 이슈에서는 AWS CLI에서 제공하는 API를 사용하여 AWS 에서 제공하는 인스턴스별 하드웨어 특성을 수집하는 모듈을 구현합니다.

```
aws ec2 describe-instance-types
```

우선 core, ram, network 의 기본적 특성으로 초기 구현을 목표로 하고, 
후에 별도로 프로세서, frequency 등 세부 특성을 조사하여 범위를 확장시킬 수 있도록 합니다.

#199 이슈의 aws 세부 구현 이슈입니다.

**Comment by wynter122** [comment]
@kmu-leeky 교수님 해당 이슈에서 aws 수집 모듈은 구현했는데, GCP처럼 Lambda로 구성하지는 않았습니다. AWS까지 lambda에서 구동하도록 할까요?

**Comment by kmu-leeky** [comment]
원타임이라면 람다가 나을수 있을것 같은데, 아직은 주기적인 작업이 주로 일어나지 않을것 같으니, 우선은 그냥 둘까? 람다로 옮기는데 어느정도의 노력이 필요할것 같아?

**Comment by wynter122** [comment]
지금 코드는 쉘 스크립트로 데이터를 받아서 전처리하는 구조라 lambda에서 sh 파일이 잘 작동한다면 작업량이 크진 않을 것 같습니다. 하지만 만약 sh 파일 사용이 매끄럽지 않다면 boto3 sdk 사용으로 변경해야하는데, 이렇게되면 코드 수정이 많이 필요할 것 같습니다.

**Comment by kmu-leeky** [comment]
그러면 이건 잠시 pause 해두고 논문에 들어갈 데이터 수집 및 분석에 조금 더 에너지를 쏟도록 하자.

**Comment by wynter122** [comment]
네 그러면 aws는 로컬에서 실행하여 S3에 올려두도록 하겠습니다.
