### ISSUE TITLE
GCP 인스턴스별 하드웨어 특성 수집 모듈 구현

### ISSUE THREAD

**Issue by wynter122** [ddps-lab/spotlake#250]
### 목표
본 이슈에서는 GCP 의 인스턴스별 하드웨어 특성 수집 모듈을 구현합니다.
아래 API를 사용합니다.
https://cloud.google.com/compute/docs/reference/rest/v1/machineTypes/aggregatedList?apix_params=%7B%22project%22%3A%22strong-aegis-356404%22%7D

API의 수집 결과는 [코멘트](https://github.com/ddps-lab/spotlake/issues/199#issuecomment-1280976134)에 설명되어있습니다.

### 수집 과정
해당 API는 zone 별로 가능한 instance를 제공해주는 것으로 보입니다.
따라서, zone을 region으로 특정하여 분류한 뒤 다음 사항들을 확인해야합니다.
- 각 region 내부에서 zone 별로 나뉘는 지원 instance 간에 spec 차이는 없는지
- 전체 region에서 instance 간에 spec 차이는 없는지

위 두 사항을 만족한다면 instance specification을 수집,
후 별도 이슈로 region 별 지원 instance type data까지 확보하는 과정을 이어나갈 수 있도록 하여 #188 이슈 해결 진행해 볼 예정입니다.

**Comment by HyeonYoung-Lee** [comment]
우선 AggregatedList API를 토대로 GCP 하드웨어 특성 수집구현은 완료했습니다.
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/72314987/200763779-dbb91f80-10fc-4d2f-8ca9-10f7fda23bdd.png">

결과 dataframe pickle 파일:
[gcp_hardware_feature.pkl.zip](https://github.com/ddps-lab/spotlake/files/9968301/gcp_hardware_feature.pkl.zip)

현재 aws 특성 수집 모듈 PR이 merge 되지 않아 gcp 푸시를 올리면 커밋이 겹쳐 PR을 생성하지는 않았고, 결과 공유 차원에서 코멘트를 남기려 합니다. aws PR 이 merge 되면 gcp PR 올려 코드리뷰 진행하겠습니다.

구현 중 궁금한점은 다음과 같습니다.
- gcp의 경우 API에서 제공하는 정보가 많이 모자라서 AWS 와 매칭할만한 요소들이 cpu 개수, memory size, gpu 타입, gpu 개수 등이 있습니다. lscpu로 170개 인스턴스타입을 모두 실행하기에는 부담이 있을 법 한데, 먼저 매칭 가능한 인스턴스들을 추린 후 lscpu로 추가 수집을 진행하는 시나리오가 적절할까요?
- gcp의 수집 정보중, 최대 PersistentDisk의 사이즈와 개수를 수집하는것이 의미있을지 모르겠습니다. 해당 인스턴스 타입에서 영구디스크를 추가하는 용량이 그 정보만큼 가능하다는 것 같은데, 불필요한정보라고 생각이듭니다. 다만 해당 정보 외에 스토리지 볼륨 관련 정보가 없어 우선 데이터셋으로 구성해놓은 상태입니다. 
- gcp는 정보가 많이 없어서 따로 함수화 시키지는 않고 하나의 python 파일 내에서 API 수집과 전처리를 진행하도록 코드를 구성했습니다. 다만, aws는 raw data를 따로 로컬에 저장하여 후에 API 수집 오류가 발생하여도 이전에 수집한 결과를 토대로 전처리가 가능한 상태인데 GCP도 수집과 처리를 분리하여 raw data를 저장하는것이 좋을까요?
