### ISSUE TITLE
람다 실행 시 에러 공지를 슬랙으로 보내는 시스템의 구현 가능성 논의

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#253]
https://medium.com/orion-innovation-turkey/cloudwatch-alarms-b87ca6802e4

람다+cloud watch+sns 를 활용한 에러 공지 시스템.
우리도 람다를 이용한 데이터 컬렉터가 많은 만큼 활용해볼만할듯. practice 관점에서도 좋고.

**Comment by kh3654po** [comment]
이 이슈도 close하겠습니다.
