### ISSUE TITLE
코드에서 상수 및 경로 등 여러 코드에서 널리 사용되는 변수들은 config 파일로 분리하기

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/spotlake#255]
현재 다양한 소스코드에서 같은 파일 경로 프로젝트명 등이 사용되고 있는데, 이걸 매 코드마다 별도로 관리하기에 좋아보이지 않음.
전체 코드에서 활용 가능한 상수를 저장하는 config 파일을 하나 만들어서 해당 파일에 여러 상수 저장 후 여러 코드에서 참조해서 쓰도록 해야할듯 함.

**Comment by kmu-leeky** [comment]
@red0sena  오늘 회의 내용 정리 부탁.

**Comment by red0sena** [comment]
### 금일 회의 내용 정리입니다. 

1. [spotlake/collection/aws/lambda/collector](https://github.com/ddps-lab/spotlake/tree/main/collection/aws) 폴더삭제


2. [spotlake_query/blob/main/api-lambda/sungjae-timestream-query.py](https://github.com/ddps-lab/spotlake_query/blob/main/api-lambda/sungjae-timestream-query.py) 파일 삭제


3. [spotlake_query/blob/main/api-lambda/spotrank-calc-avg.py](https://github.com/ddps-lab/spotlake_query/blob/main/api-lambda/spotrank-calc-avg.py)파일 삭제


4. [spotlake/tree/main/migration](https://github.com/ddps-lab/spotlake/tree/main/migration) 폴더를 별도의 spotlake-migration 리포지토리생성하여 이관

    - [spotlake/tree/main/utility](https://github.com/ddps-lab/spotlake/tree/main/utility)의 [spotlake/blob/main/utility/slack_msg_sender.py](https://github.com/ddps-lab/spotlake/blob/main/utility/slack_msg_sender.py)외 모든 파일을 spotlake-migration으로 이관


5. [spotlake/tree/main/frontend](https://github.com/ddps-lab/spotlake/tree/main/frontend) 폴더를 따로 리포를 생성하는 것을 고려
    - 원래 프론트엔드의 리포지토리가 있으면 그곳에서 하는것으로


6. 연구실의 논문용 코드(matplotlib위주) 모아두는 리포지토리 생성
    - [spotlake/tree/main/analysis](https://github.com/ddps-lab/spotlake/tree/main/analysis)폴더 삭제후 이 리포지토리로 이관
    - [spotlake/tree/main/preprocessing](https://github.com/ddps-lab/spotlake/tree/main/preprocessing)폴더가 논문용이 맞으면 논문용 리포지토리로 이관


7. [spotlake/tree/main/collection](https://github.com/ddps-lab/spotlake/tree/main/collection)폴더 collector로 이름 변경
    - collector 하위에 다음과 같이 collector분리
        - 가격 collector(spot-dataset)
        - 하드웨어 collector(hardware-dataset)


8. [spotlake/tree/main/monitoring](https://github.com/ddps-lab/spotlake/tree/main/monitoring) 폴더 삭제
    - spotlake-query 리포지토리에서 관리


9. spotlake_query spotlake-query로 리포지토리명 변경


10. slack webhook url [Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html)로 전달

**Comment by kmu-leeky** [comment]
오케이. 경환아 땡큐.

회의에서 나온 내용을 이슈화 해서 트래킹 해보자. 이슈로 정리는 내가 해둘께.
