### ISSUE TITLE
쿼리 처리 람다의 요청 횟수를 모니터링 하여 많은 경우 슬랙으로 메시지 전송 기능 구현

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/spotlake#257]
람다를 이용한 쿼리가 많은 자원을 소모할 수 있기에 단기간에 많은 요청이 들어온다면 (예: 1분에 10회 이상), 이를 슬랙의 모니터링 채널에 공지하는 시스템이 필요함

**Comment by kmu-leeky** [comment]
쿼리 함수 실행 횟수를 매일 슬랙으로 공지를 보내게끔 하는게 적절할듯.

**Comment by kmu-leeky** [comment]
이작업은 수혁이가 진행을 하도록 하자. @cg10036  
2가지 기능을 구현하면 좋겠어.
우선 단기간에 많은 쿼리가 들어올 경우 (1분에 10회 이상) 즉시 system-monitoring 에 메시지 공지 오게 하기.
다음으로 매일 아침에 해당 람다가 그 전날 동안에 호출 및 실행된 횟수를 카운트 해서 system-monitoring 채널로 쿼리 횟수를 공지 오게끔 하면 될것 같아

클라우드 와치 + 람다를 주로 사용하게 될것 같아.

수혁아. 언제쯤 마무리 될런지 추산해서 공유해줘.

**Comment by cg10036** [comment]
전체 람다를 카운팅해서 1분에 10회 이상인가요, 아니면 각각의 람다를 카운팅해서 해야하나요?
오늘, 늦어도 내일안에 가능할 것 같습니다.

**Comment by kmu-leeky** [comment]
쿼리를 처리하는 람다가 하나 밖에 없어서 해당 람다가 요청되는 횟수를 카운트 하면 될것 같아.
@chris0765  람다 지역 및 이름을 알려줘.

**Comment by chris0765** [comment]
@cg10036 spotrank 계졍에서 us-west-2(Oregon) 지역의 spotlake-timestream-query 람다를 카운팅하시면 됩니다.

**Comment by cg10036** [comment]
TimestreamQueryAlarm Cloudwatch에서 TimestreamQueryAlert Amazon SNS를 통해 timestream-query-alert 람다 함수를 실행시켜 웹훅을 전송합니다.
람다 함수 환경변수에 HOOK_URL 변경하면 됩니다.

<img width="716" alt="스크린샷 2022-11-23 오전 1 40 02" src="https://user-images.githubusercontent.com/30382481/203371035-524c5ec5-8f06-4f7b-abc4-6cfcdaf0f1fb.png">
(1분에 1회 이상으로 테스트)

아침마다 실행된 횟수 카운트하는것은 내일 작성하겠습니다.

**Comment by kmu-leeky** [comment]
오케이 수혁아 잘했다. TimestreamQueryAlarm cloudwatch 에서는 쿼리 람다의 (spotlake-timestream-query) 실행 횟수를 모니터링 하고, 이게 threshold 를 넘어서면 (현재 1분 1회) SNS 발생 후, 람다 실행 (timestream-query-alert ) 후에 슬랙으로 메시지 전송한다는 거지? 시퀀스 좋아보인다. timestream-query-alert  코드에 대해서만 리뷰 진행해보면 좋겠다. PR 생성 부탁해. spotlake-monitoring 리포에 추가하면 좋을것 같아.

**Comment by kmu-leeky** [comment]
spotlake-monitoring 이 아니라 spotlake-query 에 monitoring 폴더이겠다.

**Comment by cg10036** [comment]
@kmu-leeky spotlake-query 리포지토리가 보이지 않습니다.

**Comment by kmu-leeky** [comment]
아 오케이. 수혁아 추가해줄께.

**Comment by cg10036** [comment]
쿼리 실행 횟수 웹훅으로 전송하는것 작성 완료했습니다.
<img width="455" alt="스크린샷 2022-11-24 오후 9 36 20" src="https://user-images.githubusercontent.com/30382481/203786177-df9bd9bb-43e0-41bd-ab89-c7016f3b684a.png">

웹훅 주소 슬랙으로 보내주실 수 있나요?

**Comment by cg10036** [comment]
시간은 UTC기준으로 표시합니다.
