### ISSUE TITLE
10월 28일 부터 10월 31일까지 데이터 유실 부분 복구하기

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/spotlake#264]
kmu-bigdata 계정에 있는 원본 파일 및 time stream 으로 부터 데이터 복사해오기.

**Comment by kmu-leeky** [comment]
이것도 작업이 안되고 있었네. @chris0765 @kh3654po  함께 작업하기로 했으니 일정 이야기 나눠보고 언제까지 마무리 지을런지 공유해줘.

**Comment by kh3654po** [comment]
넵 얘기해보고 올려드리겠습니다.

**Comment by kmu-leeky** [comment]
오케이. 석현아 좋다. 재일이에게 전해 들은 이야기를 간단히 먼저 정리해줄래? 같이 검토해보고 진행하자. 그리고 이제는 깃허브-슬랙 연동이 어느정도 해결이 되어서 나 멘션 안해줘도 괜찮을것 같아.

**Comment by kh3654po** [comment]
데이터 유실된거 복구하는 코드를 이미 구현한게 있어서 그 코드를 ec2인스턴스에서 실행하면 될거같습니다. 

이제 주의해야할점은 
1. 맨처음 정상작동 테스트 (코드의 BUCKET_NAME, UPLOAD DATABASE NAME, UPLOAD TABLE NAME 뒤에 -test 붙이는 것 확인하고 실행)
2. 쿼리 기간 설정 확인
3. spotrank s3에서 수집이 끊긴 시점의 raw data 받아와서, migration 코드와 같은 디렉토리에 'latest.csv.gz' 라는 형식으로 존재하게끔 수정(매 테스트 마다)
4. vCPU:8개 인스턴스에서 진행, aws configure 잘 설정할 것
이렇게 4개 있습니다.

제가 ec2 다루는거는 수업시간 실습때 해본게 다라서 해보면서 하려면 시간은 좀 걸릴거같습니다.

**Comment by kmu-leeky** [comment]
오케이 석현아. 1번은  임시 데이터 저장소로 사용하는 용도인거지?
3번은 모든 raw data 가 라면 10분마다 한번씩 수집되어 있을텐데, 매번 해당 파일을 latest.csv.gz 로 수정을 한다는 이야기야?
그런 후에 compare 모듈로 데이터를 db 에 추가하는 단계?

**Comment by kmu-leeky** [comment]
그리고 이건 석현이가 정리를 해줘도 좋은데 재일이가 조금 더 구체적으로 문서로 남겨두는게 좋을것 같아.

**Comment by chris0765** [comment]
spotlake-migration 레포지토리에 README 파일을 추가하였습니다.
