### ISSUE TITLE
AWS data collector 와 workload 수집 모듈의 분리 및 별도 구동

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/spotlake#265]
collector 는 매 10분마다 동작하는 cronjob 으로
workload 수집 모듈은 하루에 한번 동작하는 cronjob 으로.
로그 메시지 수집 가능하도록 구동 시키기
workload 수집 모듈은 매일 해당일의 워크로드를 업로드 함. 업로드 객체 주소에 날자를 포함하여 모든 데이터를 보관하도록 함
collector 는 매 동작마다 (10분) S3 에 있는 당일의 워크로드를 다운 받아와서 collection 진행.
S3 에서 다운 받은 워크로드는 로컬에 latest 파일로 저장하여 S3 로 부터 파일을 다운 받을수 없을 경우 로컬 파일을 활용 --> 워크로드가 업데이트 되지 않더라도 주요 워크로드에 대해서는 지속적으로 수집이 되게끔 하고자 함.

**Comment by kmu-leeky** [comment]
@chris0765  재일아. 이 이슈도 너무 오래 그냥 두고 있다. 얼른 해버리자. 언제까지 마무리 지을래?
