### ISSUE TITLE
Query를 이용하여 데이터를 가져올 때, Savings가 frontend에서 계산되지 않는 오류

### ISSUE THREAD

**Issue by j-myeong** [ddps-lab/spotlake#267]
#261 에서 쿼리문을 이용하여 데이터를 받아올 시, Savings가 보여지지 않는 오류가 있습니다.

기존 메인에서 보여주는 코드 및 [#192-comment](https://github.com/ddps-lab/spotlake/issues/192#issuecomment-1251788601) 참고하여 frontend에서 Savings가 표시되도록 수정하도록 하겠습니다.

@H0zzae 이슈 트래킹용으로 언급드립니다.

**Comment by wynter122** [comment]
resolved at #275
