### ISSUE TITLE
Azure console 에서 제공되는 spot 가격 수집 하기

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#274]
console 에서 제공되는 APU 로 스팟 가격 수집 후 이를 http 기반 가격 정보와 비교해보기
region, instance type 의 구성 및 데이터 갯수등을 비교하여 어떤 데이터를 최종적으로 활용할지 결정 필요.

**Comment by cg10036** [comment]
Azure CLI에서는 가격을 수집하는 부분을 찾지 못했습니다. 기존에 사용하던 API, 현재 새로 작성할 때 사용한 API 이렇게 두개를 비교하면 될까요?

**Comment by cg10036** [comment]
research-issues#145 (새롭게 수집된 spot price 수집 모듈의 데이터 확인 #145)와 동일한 내용인것 같습니다. 해당 이슈 닫아도 될까요?

**Comment by kmu-leeky** [comment]
응 수혁아 이건 닫아도 되겠다. close.
