### ISSUE TITLE
AWS Athena이용 슬랙에 AWS 데이터 수집 개수 전송

### ISSUE THREAD

**Issue by red0sena** [ddps-lab/spotlake#291]
#200

AWS Athena를이용하여 AWS데이터 수집 개수를 report하는 이슈입니다.

https://docs.aws.amazon.com/ko_kr/athena/latest/ug/getting-started.html

**Comment by red0sena** [comment]
#293 PR 완료하였습니다.


기존 timestream을 이용하여 query하던 것에서 athena를 이용하여 query하는 것으로 변경하였습니다.
spotlake계정의 spot-data-count lambda함수에서 UTC기준 매일 00:05에 함수가 작동되며 1분이내로 완료됩니다.

**Comment by red0sena** [comment]
# Athena를 이용한 system-monitoring

aws데이터 수집 개수를 파악하기 위해 람다함수를 이용해 매일 슬랙의 system-monitoring채널로 메시지를 보내고 있습니다.

기존 kmu-bigdata에서는 timestream에 모든 데이터를 업로드해 하루동안 수집된 모든 데이터를 카운트 하였지만

spotlake계정에서는 timestream에 changed-row만 저장하기에 하루동안 수집된 데이터를 확인하는데 어려움이 있었습니다.

그래서 s3에 저장하는 raw데이터를 count하는 방식으로 진행하려고 하였습니다.

csv.gz파일로 저장되어 있는 하루치 파일 144개를 모두 가져와서 람다의 임시 스토리지에 저장한 후 df로 만든 후 전처리 하고 그 길이를 모두 더하여 수집된 데이터의 개수를 구하였습니다.

그러던 중 교수님의 추천으로 athena를 알게 되었습니다.

athena는 표준 SQL을 사용해 S3에 저장된 데이터를 간편하게 쿼리할 수 있습니다. 또한 서버리스 플랫폼이기에 관리할 인프라가 없습니다.

[https://kangprog.tistory.com/118](https://kangprog.tistory.com/118) 위 블로그를 참조하여 코드를 구성하였습니다.

```c
athena_handler.start_query_execution(
            QueryString=f"""
                 CREATE EXTERNAL TABLE IF NOT EXISTS aws_ingestion_monitor(
                    instancetype string,
                    az string,
                    spotprice double,
                    region string,
                    sps int,
                    ondemandprice double,
                    interruptfrequency double,
                    savings int
                  ) 
                  ROW FORMAT DELIMITED
                  FIELDS TERMINATED BY ','
                  LINES TERMINATED BY '\n'
                  LOCATION 's3://spotlake/rawdata/aws/{s3_path_date}'
                  TBLPROPERTIES ("skip.header.line.count"="1"); 
                 """,
            ResultConfiguration={'OutputLocation': f's3://spotlake-count-log/create-athena-table/{s3_path_date}/'}
        )
```

테이블을 생성하는 코드입니다. S3에 저장된 DDL문을 사용하여 raw데이터의 포맷에 맛게 스키마를 설정해주고 개수를 rawdata의 경로를 가리켜주면 테이블이 생성됩니다.

```python
def query_athena(query_string):

    query_start = athena_handler.start_query_execution(
        QueryString=query_string,
        ResultConfiguration={'OutputLocation': f's3://spotlake-count-log/query_athena/{s3_path_date}/'})

    while True:
        query_status = athena_handler.get_query_execution(
            QueryExecutionId=query_start['QueryExecutionId'])
            query_execution_status = query_status['QueryExecution']['Status']['State']

        if query_execution_status == 'SUCCEEDED':
            result = athena_handler.get_query_results(QueryExecutionId=query_start['QueryExecutionId'])
            break

        print("sleep")
        time.sleep(1)

    print(result)
```

데이터를 쿼리하는 코드입니다. query문을 작성하여 요청하면 결과를 바로 리턴해 주는 것이 아닌 QUEUED | RUNNING | SUCCEEDED | FAILED | CANCELLED 5가지 상태로 status가 나타나고 이 중 SUCCEEDED상태가 되었을 때만 쿼리 결과를 확인 할 수 있습니다. 이는 Athena는 서버리스 대화식 쿼리 서비스이고 Athena에 쿼리를 제출하면 쿼리가 백엔드의 리소스 풀에서 실행, 이러한 리소스는 해당 리전의 모든 사용자가 공유하기 떄문에 쿼리가 실행되기 전에 일시적으로 대기열에 있을 수 있습니다([https://aws.amazon.com/ko/premiumsupport/knowledge-center/athena-queries-long-processing-time/](https://aws.amazon.com/ko/premiumsupport/knowledge-center/athena-queries-long-processing-time/))

위와 같은 athena 쿼리로 실행했을 때 일일이 s3에서 파일을 다운받았을 때와 같은 결과를 가져왔지만 성능 면에서 큰 차이를 보였습니다.

s3에서 파일을 다운받았을 때 

- 실행시간 37초
- 최대메모리 사용 194 MB

athena쿼리를 이용하였을 때

- 실행시간 6초
- 최대 메모리 사용 75MB

**Comment by red0sena** [comment]
[#1](https://github.com/ddps-lab/spotlake_query/pull/1) 에서 구현 완료하였으므로 close하겠습니다.

**Comment by red0sena** [comment]
@kmu-leeky for tracking

**Comment by kmu-leeky** [comment]
땡큐!
