### ISSUE TITLE
Query시 오류 케이스 발견 및 처리 필요

### ISSUE THREAD

**Issue by H0zzae** [ddps-lab/spotlake#294]
Query 시 오류 케이스들과 해당 오류에 대한 가이드라인 문구 적용을 위한 이슈입니다.

**Comment by H0zzae** [comment]
Network Error
<img width="408" alt="image" src="https://user-images.githubusercontent.com/39540561/200510800-cf5a3969-6128-4a85-b646-1a39f5622832.png">
현재는 아래와 같은 문구입니다. <img width="479" alt="image" src="https://user-images.githubusercontent.com/39540561/200512886-5b72491b-3295-4fad-b5e5-adfa8583450e.png">

**Comment by chris0765** [comment]
a network error occured 에러는 백엔드 쿼리 코드에서 오류가 발생하였을 경우, response가 발생하지 않기 때문에 발생하는 에러입니다.
'쿼리 에러 발생, 이메일로 컨택 바람'과 같은 의미의 문구가 적당할 듯 합니다.

**Comment by chris0765** [comment]
네, 브라우저에서 reponse를 얻을 수 없을 때 자체적으로 발생시키는 에러입니다.
백엔드 쿼리 코드에서 어떤 에러가 리턴되는지는 에러가 발생한 모듈과 라인에 따라서 달라질 듯 합니다.
이를 프론트에 전달해주도록 하려면, 각 모듈 호출 라인마다 try-except 구문을 사용하면 에러 response를 전달할 수 있을 듯 합니다.

**Comment by kmu-leeky** [comment]
오케이. 클라이언트 자체에서 발생시킨다고 보면 되겠구나. 쿼리 모듈에서 발생하는 에러 메시지 경우를 조금 더 고려해봐야 할테니 지금 당장 수정은 하지 못하더라도 to do list 에 두고 나중에 구현을 진행해보자.

**Comment by j-myeong** [comment]
넵. httpStatusCode가 403이나 500일 경우에는

```
{
    "Status": (403) or (500)
    "Data": "Error String"
}
```
로 돌아와서 Error String을 Alert로 처리하면 될까요?

**Comment by kmu-leeky** [comment]
403 은 Invalid Access
500 은 Internal Server Error
로 하면 될듯 해요.

**Comment by chris0765** [comment]
Alert보다는 기존 쿼리 리턴값 개수 표시 메세지 박스와 같은 형태로 에러 스트링을 표시해주는것이 좋을 것 같습니다.

**Comment by j-myeong** [comment]
넵 그러면 Status가 403 이면 Invalid Access를, 500 이면 Internal Server Error 를 출력하도록 진행하겠습니다.

**Comment by chris0765** [comment]
@j-myeong 혹시 작업이 언제쯤 완료가 될까요?
지금 확인해보니 따로 403, 500 관련 메세지 출력이 확인되지 않는 듯 합니다.

**Comment by j-myeong** [comment]
저번에 작업 완료했었는데 반영이 잘 안된 듯 합니다. 확인 후에 바로 처리하겠습니다.

**Comment by chris0765** [comment]
@j-myeong 혹시 403, 500만 리턴하는 api가 필요하시면 제작해드리도록 하겠습니다.

**Comment by j-myeong** [comment]
@chris0765 제작해주신다면 배포하면서 테스트 진행해보겠습니다!

**Comment by j-myeong** [comment]
@chris0765 말씀해주셨던 문제를 확인하여 조치하였습니다! 테스트 후 close 해주시면 감사하겠습니다.

**Comment by chris0765** [comment]
확인했습니다.
