### ISSUE TITLE
벤더별 버튼 크기 규격화

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#299]
<img width="463" alt="스크린샷 2022-11-07 오후 3 00 58" src="https://user-images.githubusercontent.com/66048830/200673497-da285a4e-35ec-4bf1-b5ba-3ef6f6faa30a.png">

AWS와 GCP는 큰 차이가 없지만, Azure 혼자서 버튼의 가로폭이 눈에 띄게 좁음.
세 벤더의 버튼 크기를 통일하면 좋을 것 같음

**Comment by kmu-leeky** [comment]
찬성 한표.

**Comment by j-myeong** [comment]
넵. 말씀해주신 내용 반영하여 각 벤더 크기를 180px로 고정하였습니다.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/50445943/200715666-52dab828-8e28-4dc6-ab24-99c6efc3f2f9.png">

**Comment by wynter122** [comment]
resolved at #301
