### ISSUE TITLE
Google Cloud 로딩 바 위치 수정

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#304]
![image](https://user-images.githubusercontent.com/66048830/200988300-c73de4bf-b62b-4b20-aabd-237761e7152a.png)

로딩바가 테이블과 겹침
타 벤더에 비해서 더 위쪽에 위치해 있는 듯 함

**Comment by kmu-leeky** [comment]
이게 GCP 는 행이 2개라 (Calculator, VM Instance) 발생을 하는것 같더라고. 롱텀으로 Calculator 컬럼을 쿼리 옵션으로 빼고 행을 1개로 만들면 괜찮아 질것 같기는 한데, 작업하는 기간이라도 프로그레스바 위치를 조금 조정해주면 좋기는 하겠다.

**Comment by j-myeong** [comment]
프론트엔드 작업 상황입니다. 다른 vendor와 달리, GCP를 구성하는 Header의 행이 2개로 구성되어 있어서 발생하였었고, 현재 프로그레스 바의 위치를 조금 더 아래쪽으로 수정하였습니다.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/50445943/201265631-86664d8a-45ee-406e-836d-5571b3928a69.png">

**Comment by kmu-leeky** [comment]
resolved by #308
