### ISSUE TITLE
Spotlake 페이지의 콤보박스가 스크롤시 같이 움직임

### ISSUE THREAD

**Issue by wynter122** [ddps-lab/spotlake#305]
문제 상황은 아래링크의 동영상을 참고해주세요.
https://www.youtube.com/watch?v=jA_rNwpABiM

날짜 선택은 스크롤 하면 바로 사라집니다.
날짜 선택처럼 스크롤시에 콤보박스가 사라지게 처리하거나, 혹은 콤보박스가 고정되어있을 필요가 있는 것 같습니다.

**Comment by j-myeong** [comment]
프론트엔드 상황 공유드립니다. Select 박스와 관련하여 말씀해주신 스크롤 시 사라지게 하거나 고정되어 있는 옵션이 현재 사용하는 라이브러리(MUI) 에서 구현이 가능한지 확인해보았으나 https://mui.com/material-ui/react-select/ 을 참고해보니 Select 선택 시, 콤보 박스를 제외한 외부에서 전체적인 스크롤 제한이 걸리도록 해둔 것 같습니다. (콤보박스에서 선택을 진행하거나, 포커스 아웃 시에만 스크롤 동작)

현재 https://spotlake.github.io 에 테스트 목적으로 위와 동일하게 외부 스크롤 제한 방식을 채택하였는데 확인해주시면 감사하겠습니다.

아래 사진은 Select 선택 시, 외부 스크롤 바가 사라지는 모습입니다.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/50445943/201266771-832ff98d-4ec6-4d9e-b6ed-082522079d3a.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/50445943/201266784-b0ae1c35-dc3d-4ae9-b146-5e1a8154ba42.png">

**Comment by wynter122** [comment]
제가 생각하기에 베스트는 외부영역 스크롤 시 콤보박스가 접히는 방향이 나을 것 같지만, 구현이 어렵다면 지금 구현하신 방법을 채택해야 할 것 같습니다. 
다만 스크롤 바가 사라지는게 한눈에 들어오는 요소는 아니다보니, 사용자 입장에서는 갑자기 스크롤이 막힌다 라고 느껴질 것 같긴합니다..!
@kmu-leeky @chris0765 @red0sena

**Comment by kmu-leeky** [comment]
오케이. 선택 메뉴 외부로 커서가 있다면 스크롤이 안되게끔 하는 방법이네요. @wynter122  이야기한 단점이 있겠네요. 그래도 구현의 난이도를 생각해본다면 지금 spotlake.github 페이지에서 보이는 정도로 스크롤이 되지 않아도 괜찮아 보이네요.

**Comment by j-myeong** [comment]
넵. 그러면 현재 작업한 부분까지 적용하여 PR 올리도록 하겠습니다. 이번 이슈는 @H0zzae 와 함께 말씀해주신 구현방법에 대해 조금 더 생각해보도록 하겠습니다!

**Comment by kmu-leeky** [comment]
오케이. PR 만들때 팁 한가지. PR description 에 Resolves #305 이런식으로 이슈 번호를 기재해주면 PR 이 머지되면서 이슈도 함께 close 되니 그렇게 해주면 좋을듯 해요.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by j-myeong** [comment]
넵. 감사합니다 참고하겠습니다!

**Comment by kmu-leeky** [comment]
resolved by #308
