### ISSUE TITLE
Spotlake 테이블의 컬럼은 가운데 정렬이 안됨

### ISSUE THREAD

**Issue by wynter122** [ddps-lab/spotlake#306]
#288 에서 테이블 가운데 정렬 이슈를 다뤘는데, 현재 확인해보니 테이블의 데이터만 정렬이 되어있고 컬럼은 그대로 인것 같습니다.
통일성을 위해 컬럼도 정렬하는게 어떨까요?

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/72314987/201046696-e4965bcf-e4fb-4a99-b186-87ca3b28c313.png">

**Comment by j-myeong** [comment]
넵. 말씀해 주신 내용 고려하여 HeaderAlign 옵션을 사용하여 현재 중앙 정렬 완료하였습니다.

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/50445943/201266127-382855c9-cc33-48bd-9335-886aca384933.png">

**Comment by kmu-leeky** [comment]
resolved by #308
