### ISSUE TITLE
슬랙의 webhook url 을 코드에서 제거하는 방안 구현

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#309]
코드에 url 을 포함하지 않고 EC2 인스턴스의 경우 parameter store 를 활용하고, 람다의 경우에는 environment variable 을 통해서 webhook url 을 알아와서 메시지를 포스팅 하도록 수정하기.

**Comment by kmu-leeky** [comment]
@kmu-leeky @kh3654po  for tracking

**Comment by kh3654po** [comment]
https://m.blog.naver.com/skykbc/221463791602를 참고해서 parameter store를 사용해봤습니다. 그 결과 url을 코드에서 제거 할 수 있는 것을 확인했습니다.

<img width="529" alt="msg_sender" src="https://user-images.githubusercontent.com/54831356/201612461-3b5133b2-b40c-41b4-af14-626c07709084.png">

<img width="533" alt="result" src="https://user-images.githubusercontent.com/54831356/201612485-4498c298-3f2e-49e0-a358-9290a4742582.png">

**Comment by kmu-leeky** [comment]
오케이. 석현아 완료되면 코드 리뷰를 진행하자. 한가지 고려할것이 해당 모듈은 EC2 를 통해서 파라미터로 전달될수 있는데, 람다에서 실행되는 경우에는 람다의 환경 변수로도 전달될 수 있어. 2가지 방법을 다 시도해보고 성공하는 곳에서 url 을 받아오는 방식으로 해야 하지 않을까 싶어. 해당 모듈은 ec2, 람다 상관없이 동시에 사용이 되어야 할것 같아.

**Comment by kh3654po** [comment]
해당 모듈이라는게 slack_msg_sender가 맞을까요? 현재 람다의 환경변수로 전달되는 부분은 레퍼런스를 찾아보고 있습니다. 한번 람다로도 시도해보겠습니다.

**Comment by kmu-leeky** [comment]
응 석현아. slack_msg_sender 맞아. 해당 파일 및 함수 안에서 webhook url 을 자동으로 알아오면 해당 api 를 호출하는 곳에서는 다른것 신경 안쓰고 그냥 slack_msg_sender() 만 호출하면 되니 이상적이지.

**Comment by kh3654po** [comment]
계속  보는데 잘모르겠습니다. 만나서 얘기해 볼 수 있을까요?

**Comment by kmu-leeky** [comment]
응 석현아 지금 내 방으로 와도 되겠다. @kh3654po

**Comment by kh3654po** [comment]
수업듣고왔습니다 지금 가능할까요?

**Comment by kh3654po** [comment]
lambda에서 환경변수로 url 얻어오는 것을 확인했습니다. 이제 람다에 환경변수들을 설정하면 될거같습니다.

![image](https://user-images.githubusercontent.com/54831356/202599008-8b282c1c-51b7-48ef-aa39-45ee407048f1.png)

![image](https://user-images.githubusercontent.com/54831356/202598769-215a0406-9c98-436c-adff-01dfe1125d5a.png)

**Comment by kmu-leeky** [comment]
nice!

**Comment by kh3654po** [comment]
@kmu-leeky  람다 레이어를 세팅하고 테스트해봤더니 람다에서도 메시지 전송이 잘됐습니다. 람다의 코드들을 수정 할까요?

**Comment by kmu-leeky** [comment]
오케이. 다행이네. import 구문쪽에 람다의 경우 레이어로 준비 필요 정도 코멘트로 남겨주면 좋겠다. 코드 리뷰하고 마무리짓자.

**Comment by kh3654po** [comment]
람다의 환경변수에서 영문, _, 숫자가능해서 error_notification_slack_webhook_url로 수정하겠습니다.

**Comment by kh3654po** [comment]
람다에 코드를 올렸습니다. 이 이슈는 close 할까요?

**Comment by kmu-leeky** [comment]
응 석현아 이건 close 하자.
PR 만들때 관련된 이슈에 대해서 Resolves #309 이렇게 써주면 머지 되면서 함께 close 되.

**Comment by kh3654po** [comment]
넵!
