### ISSUE TITLE
spotlake 핵심 서비스 이외의 코드 중 삭제를 하면 안되는 것들은 다른 리포지토리로 이관하기

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/spotlake#314]
- [spotlake/tree/main/migration](https://github.com/ddps-lab/spotlake/tree/main/migration) 폴더의 모든 파일을 spotlake-migration 리포지토리로 이관
- [spotlake/tree/main/utility](https://github.com/ddps-lab/spotlake/tree/main/utility)의 [spotlake/blob/main/utility/slack_msg_sender.py](https://github.com/ddps-lab/spotlake/blob/main/utility/slack_msg_sender.py) 외 모든 파일을 spotlake-migration 리포지토리로 이관
- [spotlake/tree/main/analysis](https://github.com/ddps-lab/spotlake/tree/main/analysis) 코드를 연구실 실험 결과물 저장 리포지토리로 이관
- [spotlake/tree/main/preprocessing](https://github.com/ddps-lab/spotlake/tree/main/preprocessing) 의 내용을 실험결과물 저장 리포지토리로 이관
- [spotlake/tree/main/monitoring](https://github.com/ddps-lab/spotlake/tree/main/monitoring) 의 파일을 spotlake-query 로 이관 및 monitoring 폴더 삭제

**Comment by kmu-leeky** [comment]
@chris0765  이 작업 얼른 마무리 짓자. 계속 시간 끌지 말고.

**Comment by kmu-leeky** [comment]
재일아 언제까지 마무리 지을런지 코멘트 남겨줘.

**Comment by chris0765** [comment]
오늘 안으로 마무리하도록 하겠습니다.
