### ISSUE TITLE
spotlake azure테이블이 쿼리되지 않음

### ISSUE THREAD

**Issue by red0sena** [ddps-lab/spotlake#316]
@kmu-leeky 
https://github.com/ddps-lab/spotlake/issues/211#issuecomment-1311319217

현재 spotlake에서 azure가 쿼리되고 있지 않습니다. 

이를 해결하기 위해 현재 람다에서 query string을 확인하여보니 아래와 같았습니다.

```
   query_string = f"""
        (SELECT ALL.* FROM (
                SELECT InstanceType, Region, MAX(time) as time 
                FROM "spotlake"."azure" 
                WHERE time < from_iso8601_date('{start}')
                AND InstanceType = '{instance_type}' {region_condition} {tier_condition}
                GROUP BY InstanceType, Region
                )LATEST, "spotlake"."azure" ALL 
        WHERE LATEST.InstanceType = ALL.InstanceType 
        AND LATEST.Region = ALL.Region
        AND LATEST.time = ALL.time)
        UNION 
        (SELECT * 
        FROM "spotlake"."azure" 
        WHERE time BETWEEN from_iso8601_date('{start}') and from_iso8601_date('{end}') 
        AND InstanceType = '{instance_type}' {region_condition} {tier_condition})"""
```

인스턴스 타입이 InstanceType 
인스턴스 티어가 instanceTier
리전이 Region으로 되어 있습니다.

그러나 현재 Timestream AZURE 테이블에서는

![캡처](https://user-images.githubusercontent.com/106056971/201527681-ce654918-77b4-465a-be64-14475f62a405.JPG)

instanceType, instanceTier, region으로 column명을 인식하지 못해 쿼리가 실행되지 않는 것으로 보입니다.

column명을 수정하여 다시 timestream에 업로드 한 후 쿼리를 다시 시도해 보겠습니다.

**Comment by kmu-leeky** [comment]
오케이. 벤더간 데이터 통일도 중요하니 빠르게 새롭게 테이블을 생성해서 진행해보자.

**Comment by kmu-leeky** [comment]
@chris0765  가 CORS 쪽은 봐줘야 할수도 있겠다.
그리고 지금 에러 팝업이ㅣ 네트워크 에러라고 뜨는데, 502 Internal error 라면 그걸 반영해서 보여줘야 하지 않을까하는데/

**Comment by chris0765** [comment]
cloudwatch 로그 확인 결과, Lambda 내부에서 'InstanceTier'를 조회하는 코드에서 key error가 발생하였습니다.
이를 통해 Azure의 쿼리 링크를 확인해보니, InstanceType, Region은 쿼리문에 포함되어 있지만, InstanceTier가 포함되어있지 않은 것을 확인했습니다.

우선, lambda 코드에 instanceTier가 포함되지 않은 쿼리문이 들어올 경우, 자동적으로 InstanceTier를 ALL로 취급하도록 설정해두었고, 재확인 결과 정상적으로 쿼리가 이루어집니다.

프론트엔드쪽에서 Azure의 쿼리 구성을 다시 한번 확인해주어야 할 듯 합니다.

**Comment by chris0765** [comment]
@kmu-leeky @red0sena 슬랙에 알림이 가지 않아 다시 코멘트 남깁니다.

**Comment by kmu-leeky** [comment]
오케이. 재일아 확인땡큐. 지금 쿼리에서 Tier 를 보니 선택 옵션이 ALL 밖에 없구나. 해당 옵션을 ALL, Standard, Basic 으로 바꾸고 해당 값을 쿼리에 전달해주기는 해야겠다. good catch.

**Comment by j-myeong** [comment]
넵. 현재 프론트엔드 단에서 상황 파악 중에 말씀해주신 것처럼 InstanceTier가 담기지 않고 쿼리가 전송되는 문제를 발견했습니다. 일단, #315 PR 에서 진행한 리팩토링 코드가 머지 대기중여서 진행 후에 테스트 진행해보겠습니다.

**Comment by red0sena** [comment]
현재 다시 쿼리를 시도해보니 쿼리는 성공하였으나 

<img width="1609" alt="Screenshot 2022-11-14 at 4 40 54 PM" src="https://user-images.githubusercontent.com/106056971/201602406-6f06f098-2d82-45a5-a0bf-28530838af6c.png">

위와 같이 아무런 데이터가 보이지 않습니다.

https://github.com/ddps-lab/spotlake/blob/82482fa6f9398dbd1bed4099dd3e02b4acb7155a/frontend/src/pages/demo/demo.js#L346-L348

위의 코멘트하였듯이 query_string 이슈로 Timestream azure 테이블의 column을 소문자에서 대문자로 변경하였기 때문에 발생하는 문제로 예상됩니다.

@j-myeong 이 부분도 같이 확인 부탁드리겠습니다.

**Comment by j-myeong** [comment]
현재 쿼리에서 Tier 부분이 빠져서 요청되는 부분 및 Tier 단에서 ALL / Standard / Basic 을 추가 완료하였습니다. 다만, 쿼리시에 데이터가 보이지 않는 이슈를 해결하기 위해서 column이 소문자에서 대문자로의 변경을 진행하려 하였으나, 처음 서버에서 받아오는 latest_azure.json 파일 형식에서는 소문자로 작성되어 있어서 이 부분에서의 해결이 필요할 것 같습니다.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/50445943/201617487-5229fe33-2085-4b40-95b7-77cfba38a945.png">

**Comment by kmu-leeky** [comment]
@red0sena 빠르게 작업가능? latest json 을 수정하는 방향으로.

**Comment by red0sena** [comment]
latest_azure.json 도 대문자로 변경하도록 하겠습니다.

**Comment by red0sena** [comment]
latest_azure.json 대문자로 변경 완료하였습니다.
그런데 id도 대문자로 변경해야 할까요?

**Comment by kmu-leeky** [comment]
경환아. latest_json 파일의 대소문자 변경하는건 코드 변경필요하지 않아? 코드리뷰 요청이 없었던것 같아서. 혹시 놓치고 있는게 있다면 알려주고.

코드 리뷰 단계 및 배포 파이프라인을 만들면 좋기는 할텐데,  람다/서버에서 함께 작업하다보니 자동 배포가 쉽지는 않네. 이것도 롱텀으로 시도헤보자.

**Comment by red0sena** [comment]
https://github.com/ddps-lab/spotlake/pull/319 에서 PR 완료한 후 정상 작동 확인 되면 코드리뷰 하려고 하였습니다.

지금 PR하도록 할까요?

**Comment by kmu-leeky** [comment]
2개가 같은 이슈를 해결하기는 하지만 서로 독립적인 모듈인 만큼 PR 및 코드 리뷰는 동시에 진행해도 될것 같아. 머지 할때에 둘중 하나가 먼저 머지되면 conflict 이 날 수 있는데 이건 그냥 머지해서 새롭게 커밋/푸쉬하면 잘 할 수 있을거야. 처음 해보는 것일수 있지만 많이 사용하는 기능이니 병렬적으로 코드 리뷰 및 PR 진행하자.

**Comment by j-myeong** [comment]
프론트엔드 결과 보고 드립니다. 현재 merge 후, 조회 및 쿼리 기능이 정상적으로 확인됩니다.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/50445943/201861838-ad211abd-2efd-46a5-82be-d0a6755f7bf5.png">

**Comment by red0sena** [comment]
쿼리 기능이 정상적으로 작동함을 확인하고 #319 에서 merge되었음으로 close하겠습니다.
