### ISSUE TITLE
Azure 쿼리시 Tier 정보 반영 필요

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#317]
현재 프론트에서 Azure 쿼리시에 Tier 정보가 Standard, Basic 정보 없이 ALL 만 나오고 쿼리 문에도 포함되지 않는듯 함.
해당 옵션들 추가 필요.

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/17699616/201602699-4b12d682-1d93-4710-a616-baa792750193.png">

**Comment by j-myeong** [comment]
@H0zzae 와 확인해 본 결과, 프론트엔드에서 관리하는 azure_association 파일에 Tier 정보가 추가적으로 필요할 것 같습니다. 현재는 일방적으로 값을 넣어준 상태라 추후 유지보수를 위해서 새로운 azure_association 파일이 필요할 듯 합니다.
