### ISSUE TITLE
람다 코드 업데이트 시에도 자동으로 시스템에 반영되게끔 하는 파이프라인 구성 필요

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#321]
GitHub action 을 통해서 일부 기능은 자동 배포가 되는데
EC2 및 람다 코드는 자동 배포가 되지 않음. 우선 람다 코드의 경우 자동배포가 가능하도록 GitHub action 에 배포 기능 추가.

**Comment by chris0765** [comment]
https://github.com/marketplace/actions/aws-lambda-deploy

다음과 같은 코드 구현을 통해 lambda 배포는 가능할 듯 합니다.

https://be-developer.tistory.com/51
ec2 배포는 github action과 codedeploy를 사용하면 구현이 가능한 듯 합니다.

**Comment by red0sena** [comment]
#381 , #382 PR에 github코드와 lambda코드를 통일시키는 작업을 진행하였습니다. 
이제 github -> lambda 자동배포 이슈 진행하여도 문제 없을 것 같습니다.
