### ISSUE TITLE
spotrank aws 계정의 root iam 계정 정체 파악

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#323]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/17699616/201856236-91fd95d0-7161-480d-aaf6-0587bf07552c.png">

이런 일들을 했는데 꼭 필요한 계정인가 싶어서.
다들 한번 확인 해줘.

**Comment by wynter122** [comment]
시간대를 보니 한 시점에 3번의 이벤트가 실행되는 것 같은데, 자세한건 모르겠습니다...!

**Comment by kmu-leeky** [comment]
괜히 삭제하면 뭔가 문제가 생길수도 있겠지.. 일단 조금 더 조사를 해봐야겠다.

**Comment by kmu-leeky** [comment]
3개가 각 벤더별로 3개씩이려나. 이름도 그렇고 삭제를 했으면 하는데 조금 조심스럽기는 하네..

**Comment by kmu-leeky** [comment]
삭제하기는 부담 스러운듯 함.
