### ISSUE TITLE
Azure의 하드웨어 특성 수집 모듈 lambda에서 동작하게끔 구현

### ISSUE THREAD

**Issue by wynter122** [ddps-lab/spotlake#324]
#247 이슈에서 구현한 코드를 토대로 lambda 에서 Azure의 하드웨어 특성 수집이 가능하도록 구현합니다.

위 이슈의 코드에서는 instance type, cpu, mem, iops, cpu family 를 수집중인데, 추가적으로 GPU 정보도 수집이 필요합니다.

azure hadware feature collector 코드의 위치는 `collector/instance-specs/azure` 디렉토리입니다.
collector 디렉토리 리팩토링을 진행했으니 브랜치에서 pull 하여 진행해야합니다.

lambda에서 수집 및 전처리하여 spotrank 계정의 `hardware-feature` s3 버킷 -> azure 디렉토리에 업로드하도록 구현이 필요합니다.
#250 #303 (gcp 하드웨어 특성 수집 모듈 lambda에 구현한 이슈 참고)

**Comment by wynter122** [comment]
@kmu-leeky @wynter122 for tracking

**Comment by kmu-leeky** [comment]
@cg10036  azure 하드웨어 정보 수집 모듈을 완성했다면 PR 을 만들어줘. Azure 인스턴스의 정보도 수집을 해야 할 단계 같아.

**Comment by cg10036** [comment]
#327 작성 완료했습니다.
<img width="301" alt="스크린샷 2022-11-16 오전 4 00 38" src="https://user-images.githubusercontent.com/30382481/202003324-4da53d95-32a0-4f12-9d05-929975196f9c.png">
[2022-11-15 18-58-06.453634.zip](https://github.com/ddps-lab/spotlake/files/10015428/2022-11-15.18-58-06.453634.zip)
수집된 데이터입니다.
