### ISSUE TITLE
raw 데이터 수집시 파일명의 구분자를 콜론에서 대쉬로 바꾸는것 고려

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/spotlake#325]
현재 raw data 를 봤을때 구분자가 colon (:) 인데 해당 기호를 파일명에 쓰는게 일반적이지는 않은듯 하여
시간 및 분 구분자를 dash (-) 로 바꾸는것을 고려할 필요가 있어 보임.

**Comment by kmu-leeky** [comment]
데이터 처리 요청이 많이 오는데 파일 이름이 아무래도 마음에 걸려서 공유가 꺼려진다.
파일 명에 시간, 분을 구분할때 콜론 사용하는 것을 대쉬 기호로 바꾸는 걸 얼른 작업을 하자.
이 작업을 빠르게 마치고 파일을 공유해주는게 좋을것 같아.

지금 raw 데이터 셋을 보면 azure, gcp, aws 모두 콜론을 사용하고 있네.
S3 [spotlake](https://s3.console.aws.amazon.com/s3/buckets/spotlake) rawdata/  내의 모든 객체의 이름을 바꾸는 코드를 작성해서 얼른 한번 업데이트 해보자.

이건 @wynter122  가 진행해주면 좋을것 같아.

**Comment by red0sena** [comment]
2022/11/23 10-00 부터 업로드되는 azure데이터는 시간 분 구분을 - 로 하였습니다.

**Comment by kmu-leeky** [comment]
오케이. 경환아 잘했다. 나머지 벤더들도 우선 dash 로 저장하게끔 수정하고 기존 파일 변환은 따로 진행하자.

**Comment by wynter122** [comment]
Gcp도 대쉬로 파일명 변경하도록 코드 반영 해 두었고 정상적으로 업로드 되고있습니다.
![image](https://user-images.githubusercontent.com/72314987/203685433-2e1755a4-199d-4732-b0ae-62b68f7852e7.png)

이후 전체 파일명 변경하는 작업 진행하겠습니다.

**Comment by kmu-leeky** [comment]
응 그래 좋다. aws 는 @chris0765  가 진행해줘.
과거 전체 데이터의 이름 변경은 현영이가 진행해주고.

**Comment by chris0765** [comment]
넵 알겠습니다.

**Comment by wynter122** [comment]
### spolake s3 저장 파일 명 : -> - 변경하는 작업 진행 현황

우선 변경하는 스크립트는 모두 작성하였고, 현재 테스트를 진행하려합니다. 
우선 aws 1~7월 데이터를 임시 버킷에 복제한 뒤, 임시 버킷을 대상으로 테스트를 진행하려합니다.
속도가 빠르지 않아서 오늘 밤이나 내일 오전 내로 테스트가 완료될 것 같습니다.
테스트 후, 정상적으로 바뀌는것을 확인하고 데이터에 이상이없다면 바로 spotlake 버킷의 파일명 변경하도록 하겠습니다.

작업은 aws s3api 를 사용하여 해당 버킷의 모든 object 명을 json 형태로 얻어온 뒤, 파이썬 스크립트로 txt 파일로 가공하여 다시 aws s3 mv 명령어로 파일명을 변경합니다. 쉘 스크립트를 기반으로 작성했습니다.
1. shell script
```
#!/bin/bash

aws s3api list-objects --bucket change-obj-name --query 'Contents[].{Key : Key}' > change-obj.json
python3 /Users/wynter/Desktop/tmp/change-s3/extract_key.py

i=1
while read line || [ -n "$line" ] ; do
    new_name=`echo ${line} | tr ':' '-'`
    aws s3 mv s3://change-obj-name/${line} s3://change-obj-name/${new_name}
    ((i+=1))

done < /Users/wynter/Desktop/tmp/change-s3/origin_filename.txt

```

2. extract_key.py (aws s3api로 얻어온 obj name이 json 형태로 제공되기에, 순수한 파일명만 txt 파일로 가공하여 저장)
```
import json

origin_obj_list = []
with open('/Users/wynter/Desktop/tmp/change-s3/change-obj.json', 'r') as f:
    file = json.load(f)
    
    for key in file :
        filepath = key['Key']
        origin_obj_list.append(filepath)

with open('/Users/wynter/Desktop/tmp/change-s3/origin_filename.txt', 'w') as f:
    for fn in origin_obj_list:
        f.write(fn + '\n')
```

**Comment by wynter122** [comment]
우선 로컬에서 실행하고 있는데, 30분에 5일치 정도를 변경할 수 있습니다. 
전체 객체명 변경 시간 예상해보자면 aws만 33시간이 걸릴것같습니다. 

현재 임시 버킷에서의 파일명 변경은 정상적으로 이뤄지고 있는것을 확인했습니다.
실제 spotlake s3 파일명 변경은 ec2에서 진행하려고 하는데 t2.micro 로는 너무 느릴 것 같습니다. t3.2xlarge (8 vcpu, 32 Gib ram) 사용해도 괜찮을까요?

**Comment by kmu-leeky** [comment]
응 현영아 계획을 자세하게 잘 세웠다. 코드를 보면 특별한 이슈는 없는듯 하고 잘 동작할것 같아.
하루 정도 데이터셋에 해본게 잘 된다면 큰 이슈없이 잘 동작할것 같아.
그런데 이게 서버의 연산 능력보다는 API 의 호출 시간이 오래 걸려서 시간이 지체되는것이지 않을까?
큰 서버로 바꾼다해도 큰 성능상의 이점은 없을듯 한데. 병렬로 여러 달을 동시에 처리하려고 하는 거야?
그렇다면 확실히 빠르게 끝날것 같아.

**Comment by wynter122** [comment]
우선 스크립트의 동작 자체는 정확합니다.
다만 어느 순간부터 속도가 점차 느려지다가 작동을 하지 않는것을 확인했습니다.
병렬 처리를 생각한것은 아니고, 이전에 마이그레이션때 큰 사이즈의 머신을 사용했다고 알고있어서 그렇게 하려고 했습니다. 병렬처리쪽으로 빠르게 조사해보고 시도해서 이번주내로 변경 완료하도록 해보겠습미다.

**Comment by kmu-leeky** [comment]
시간이 빠르다가 오래 걸린다는게 신기하네. 지금 코드를 보면 각 명령어들이 독립적으로 하나씩 실행이 되는듯 한데. 계속 사용할 모듈이라면 확실히  원인에 대해서 디버깅을 해볼텐데, 그렇지는 않으니 우선 작업을 마무리 짓는 방향으로 해보자.
