### ISSUE TITLE
aws raw 데이터 탐색 중 불완전 데이터 발견

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#326]
2022년 10월 1일 23시 50분 데이터에서 아래 캡쳐 그림 처럼 az 및 가격 정보가 없는 데이터 발견
[23:50:00.csv](https://github.com/ddps-lab/spotlake/files/10013327/23.50.00.csv)

<img width="535" alt="image" src="https://user-images.githubusercontent.com/17699616/201940044-4a0af182-1489-477c-b04c-aecddc8647ed.png">

**Comment by chris0765** [comment]
AZ가 제공되지 않는 데이터셋, Spot 지원 instance type에 대한 데이터만 제공하는 데이터셋 등을 outer join하기 때문에 발생하는 문제입니다.

이전에 수집된 데이터들에도 마찬가지로 들어가 있는 정보들이기 때문에, collect 방식을 수정하기보다는, Spot Instance 구성에 필요한 정보가 없는 raw들을 쿼리에서 걸러내는 방식으로 lambda 코드를 수정하는 것이 적절해 보입니다.

**Comment by kmu-leeky** [comment]
AZ 가 제공되지 않는 데이터 셋이 있구나. 그런 데이터들이라면 굳이 저장을 할 필요는 없을것 같기도 하다. 사실상 값들도 유효한 값으로 보이지는 않고. 코드를 정리해서 삭제를 하는 방향이 나을수 있겠다.

**Comment by chris0765** [comment]
불완전 데이터 처리하도록 구조 개선 완료
#395
