### ISSUE TITLE
PR #281 fail 해결하기

### ISSUE THREAD

**Issue by kh3654po** [ddps-lab/spotlake#332]
#281 pull request에서 GitGuardian Security Checks에 의해 fail이 일어나는것 해결해야한다.

**Comment by kmu-leeky** [comment]
석현아. #281  에서는 GitGuardian 이 문제가 아니라 환경 변수 이름 관련해서 코멘트 남겨뒀으니 그걸 확인해줘.

**Comment by kmu-leeky** [comment]
그리고 fail 이유는 과거 커밋 메시지에 web hook url 이 있어서인데, 과거 커밋을 없앨수는 있는데, 이게 꽤나 복잡하니, 그냥 현재 코드를 백업한 후에 해당 PR 을 없애버리고, webhook url 없는 새로운 커밋을 해서 PR 만드는게 편할듯 하다.

**Comment by kh3654po** [comment]
@kmu-leeky 코멘트를 지금 확인했네요 보고 수정해보겠습니다. 그리고 현재 main에서 새 브랜치를 생성하고 백업한 코드를 커밋해봤는데 똑같은 fail이 일어났습니다. 현재 main에 이미 url이 있는 코드가 올라가있어서인거 같습니다.

**Comment by kmu-leeky** [comment]
그런듯하네.. 해당 커밋 자체를 없애야 할수도 있겠네.

**Comment by kh3654po** [comment]
커밋 자체를 없애야 할 것 같습니다.

**Comment by kmu-leeky** [comment]
응 그래야 할것 같은데. 해볼수 있겠어?

**Comment by kh3654po** [comment]
@kmu-leeky 브랜치를 따로 파서 https://gre-eny.tistory.com/301를 보고 특정 커밋을 삭제하는 git rebase -i 를 사용해봤는데

- 커밋 삭제전 reflog
![image](https://user-images.githubusercontent.com/54831356/203080464-1a62df55-b2f6-4a1a-bf27-6845cd55cbc1.png)

- 커밋 삭제
![image](https://user-images.githubusercontent.com/54831356/203080617-ec500f04-b45d-4917-8089-1e653a8efc0e.png)

- 커밋 삭제후 reflog
![image](https://user-images.githubusercontent.com/54831356/203080771-ef937ff4-e25f-468a-a0bb-63b6a7a330c7.png)

디렉토리 확인 결과 커밋이 삭제돼서 2.txt가 사라졌지만 커밋 삭제후 relog에서 a8e4fec 커밋은 그대로 남아있어 제대로 동작한건지 잘 모르겠습니다. 깃에 익숙치않아서 잘못건드릴까 걱정되긴합니다.

**Comment by kmu-leeky** [comment]
석현아. 현재의 최신 main 브랜치로 부터 만들어서 삭제 후 PR 을 만들었다면 해당 내용의 추가/삭제 여부를 알수 있을것 같아. 다른 브랜치에서 작업을 했으니 우선 PR 을 하나 생성해볼래?

**Comment by kmu-leeky** [comment]
석현아 같이 한번 봐야겠는데.. 시간 날때 내방에서 같이 보자.

**Comment by kh3654po** [comment]
넵 수업끝나고 1시 20분쯤에 바로 방으로 가겠습니다

**Comment by kh3654po** [comment]
@kmu-leeky 이 이슈는 close 하겠습니다.
