### ISSUE TITLE
gcp raw 데이터 수집 모니터링 모듈 작성하기

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#340]
gcp 데이터가 잘 수집 되고 있는지 매일 모니터링 후 결과를 system-monitoring 채널에 공지 필요

**Comment by chris0765** [comment]
```
<2023-03-09 spotlake_workload_monitoring - GCP>
        - The number of ingested records.
            - Calculator
                - spot: 125376
                - ondemand : 125376
            - VM Instance
                - spot: 0
                - ondemand : 0
```

gcp 데이터 수집 모니터링 코드를 작성했습니다.
AWS와는 달리 s3에 저장된 credentials나 workload가 존재하지 않아 수집된 데이터의 양만 출력하도록 설정해 두었습니다.
AWS, Azure와 같은 스케쥴로 동작합니다.

VM Instance는 latest data 확인 결과 실제로 모든 데이터가 -1로 표시되어 있었습니다.
실제로도 하룻동안 수집된 모든 데이터가 na인듯 합니다.

**Comment by kmu-leeky** [comment]
그러게. gcp 의 VM 이 꽤나 오랫동안 수집이 되지 않았을수도 있겠네. 한번 확인을 해보자.

**Comment by chris0765** [comment]
정상작동 확인되어 close하겠습니다.
GCP VM 수집은 별도의 이슈로 생성하겠습니다.
