### ISSUE TITLE
데모 페이지 논문 업데이트

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#377]
About 에 있는 IISWC 2022 페이퍼 링크를 아래로 업데이트 - https://ieeexplore.ieee.org/document/9975369
그리고 PDF 로 바로 다운 받을 수 있게끔 했으면 좋겠어요 - http://leeky.me/publications/spotlake.pdf

**Comment by j-myeong** [comment]
넵. 링크 업데이트 완료하였습니다. PDF 버튼은 다음과 같게 진행하면 될까요?
<img width="342" alt="스크린샷 2023-02-13 오전 2 28 42" src="https://user-images.githubusercontent.com/50445943/218326860-e10b2459-a0de-4ffd-964c-65075081ecf0.png">
