### ISSUE TITLE
리포지토리의 람다 디렉토리 구성 변경 필요

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#378]
#321 이슈를 해결하기 위해 람다 콜렉터를 저장해두는 디렉토리의 파일 구성과 이름을 콜렉터와 동일하게 설정해둘 필요가 있음

예를 들어, azure collector의 경우 메인 함수로 lambda_function이 존재하는데, 현재 azure collector 디렉토리 내에는 azure_collect_lambda라는 이름으로 존재하고 있으며, ec2에서 사용하던 코드가 azure_collect_server 형태로 존재하고 있음.
이는 gcp도 마찬가지로, aws와 같이 ec2와 lambda 디렉토리를 분류하여 구성하고 파일 이름 등의 구성을 동일하게 유지해야 할 필요가 있음
@red0sena

**Comment by chris0765** [comment]
#381 
#382 
#390 
#391 
PR을 통해 리팩토링을 완료했습니다.

추가로 수정할만한 부분 있으시면 코멘트 남겨주시고,
없다면 close하면 될 듯 합니다.

**Comment by kmu-leeky** [comment]
nicely done!
