### ISSUE TITLE
spotlake.ddps.cloud 쿼리 불가

### ISSUE THREAD

**Issue by red0sena** [ddps-lab/spotlake#384]
<img width="993" alt="Screenshot 2023-02-13 at 5 19 08 PM" src="https://user-images.githubusercontent.com/106056971/218406680-a4b5fe78-6667-44bc-b8a9-0426faad1055.png">

현재 spotlake.ddps.cloud에서 쿼리를 할 때 "[object Object]" is not valid JSON 이라는 메시지와 함께 쿼리가 되지 않습니다. 
해당 문제 해결이 필요해 보입니다.
@chris0765

**Comment by red0sena** [comment]
https://wondev.tistory.com/107

해당 오류에 관한 블로그입니다. JavaScript에서 JQuery, Ajax를 이용해 http get요청으로 JSON 데이터를 받아올 때 발생한다고 합니다.
@j-myeong 
@H0zzae

**Comment by chris0765** [comment]
#294 이슈를 위해 백엔드에서 리턴하는 데이터의 구조를 변경해두었기 때문으로, 빠르게 프론트엔드 작업이 이루어지면 해결될 듯 합니다.

**Comment by H0zzae** [comment]
현재 받아오는 data 형식 자체가 기존과 달라진 점이 있어서 알맞게 돌아가게끔 수정 완료하였습니다.

기존 형식입니다.
`[{"InstanceType":"r6i.2xlarge","AZ":"aps1-az2","SpotPrice":0.122,"Region":"ap-south-1","SPS":3,"OndemandPrice":0.52,"IF":3.0,"Savings":76,"time":"2023-02-13 12:00:00","id":1},{"InstanceType":"r6i.2xlarge","AZ":"aps1-az1","SpotPrice":0.1497,"Region":"ap-south-1","SPS":3,"OndemandPrice":0.52,"IF":3.0,"Savings":71,"time":"2023-02-13 12:00:00","id":2},{"InstanceType":"r6i.2xlarge","AZ":"aps1-az3","SpotPrice":0.1273,"Region":"ap-south-1","SPS":3,"OndemandPrice":0.52,"IF":3.0,"Savings":75,"time":"2023-02-13 12:00:00","id":3},{"InstanceType":"d2.8xlarge","AZ":"aps1-az3","SpotPrice":1.9836,"Region":"ap-south-1","SPS":3,"OndemandPrice":6.612,"IF":1.0,"Savings":70,"time":"2023-02-13 12:00:00","id":4},{"InstanceType":"d2.8xlarge","AZ":"aps1-az2","SpotPrice":6.612,"Region":"ap-south-1","SPS":1,"OndemandPrice":6.612,"IF":1.0,"Savings":0,"time":"2023-02-13 `12:00:00","id":5},`

이번에 데이터를 받은 형식입니다. 
`"\"[{\\\"id\\\":\\\"1\\\",\\\"OndemandPrice\\\":\\\"0.105\\\",\\\"AZ\\\":\\\"2\\\",\\\"Region\\\":\\\"us-east-1\\\",\\\"InstanceType\\\":\\\"c3.large\\\",\\\"time\\\":\\\"2023-02-04 13:20:00\\\",\\\"SpotPrice\\\":\\\"0.0404\\\",\\\"SPS\\\":\\\"3\\\",\\\"IF\\\":\\\"3.0\\\"},{\\\"id\\\":\\\"2\\\",\\\"OndemandPrice\\\":\\\"0.105\\\",\\\"AZ\\\":\\\"2\\\",\\\"Region\\\":\\\"us-east-1\\\",\\\"InstanceType\\\":\\\"c3.large\\\",\\\"time\\\":\\\"2023-01-31 21:30:00\\\",\\\"SpotPrice\\\":\\\"0.0403\\\",\\\"SPS\\\":\\\"3\\\",\\\"IF\\\":\\\"3.0\\\"},{\\\"id\\\":\\\"3\\\",\\\"OndemandPrice\\\":\\\"0.105\\\",\\\"AZ\\\":\\\"2\\\",\\\"Region\\\":\\\"us-east-1\\\",\\\"InstanceType\\\":\\\"c3.large\\\",\\\"time\\\":\\\"2023-02-02 10:00:00\\\",\\\"SpotPrice\\\":\\\"0.0407\\\",\\\"SPS\\\":\\\"3\\\",\\\"IF\\\":\\\"3.0\\\"},{\\\"id\\\":\\\"4\\\",\\\"OndemandPrice\\\":\\\"0.105\\\",\\\"AZ\\\":\\\"2\\\",\\\"Region\\\":\\\"us-east-1\\\",\\\"InstanceType\\\":\\\"c3.large\\\",\\\"time\\\":\\\"2023-02-03 19:00:00\\\",\\\"SpotPrice\\\":\\\"0.0407\\\",\\\"SPS\\\":\\\"3\\\",\\\"IF\\\":\\\"3.0\\\"}]\""}`

앞으로 만약 데이터 전달 형식이 바뀌게 되면 공유부탁드립니다!

**Comment by red0sena** [comment]
쿼리가 정상 작동함을 확이하였으므로 close 하겠습니다.

**Comment by kmu-leeky** [comment]
오케이. 다들 good job! 빠르게 발견해서 잘 수정했다.
