### ISSUE TITLE
GCP 수집 모듈 수정

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#412]
현재 VM Instance의 HTML 구조가 변경되어 정상적으로 데이터를 수집하지 못하고 있습니다.

1차적으로 이 문제를 해결하고, 최종적으로는 메타데이터의 변경까지도 적응할 수 있는 시스템까지 구축하는 것이 목표입니다.

**Comment by kmu-leeky** [comment]
@wynter122  가 한번 봐주면 좋을것 같아.

**Comment by wynter122** [comment]
### vm instance pricing 수집 모듈 이슈

대략적으로 에러 원인을 파악해본 결과, https://cloud.google.com/compute/vm-instance-pricing 이 페이지의 형태가 예전가 많이 달라졌음을 확인했습니다.
가장 대표적인 변화는, 기존에 iframe으로 각 가격 테이블이 구분되어있어서 동적크롤링을 통해 iframe url을 get + 정적크롤링으로 각 url 에서 가격 얻어옴. 이 순서로 크롤링을 진행했습니다.
현재에는 iframe이 사라져서 애초에 Iframe url 을 수집할 수 없었고, 그에 따라 정적 크롤링도 수행되지 않은것으로 파악됩니다.
또한, html tag와 attribute 등 여러 요소가 많이 바뀌어서 이또한 수정이 들어가야 할 것 같습니다.

형식이 많이 바뀐 만큼 간단하게 해결할 수 있어보이지는 않지만, 추후 #190 이슈를 진행할 예정이니 빠르게 수집가능한정도로 작업을 진행하려고합니다.

**Comment by kmu-leeky** [comment]
그렇구나. 염려했던 부분이 생각보다 빠르게 발생했네. 수정이 필요한 일의 스콥을 파악해보면 진행 방향을 같이 의논해보자.

**Comment by wynter122** [comment]
### GCP vm instance pricing 수집 모듈 진행상황 공유

이슈가 발생한 url의 html 요소를 파악해본 결과, requests 로 간단하게 metadata를 받아올 수 있음을 확인했습니다.
chrome inspect 창에서는 해당 부분이 숨겨져있어서 파악에 시간이 다소 걸렸는데, GET requests를 보내면 각 테이블의 layout 정보에 metadata가 담겨져있어서 html parsing으로 처리가능할 것 같습니다.
동적 크롤링 과정이 필요가없어지면서 시간은 매우 단축된 상황입니다.

예시로 c3-standard pricing table 의 구성요소입니다.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/72314987/226920964-59cf770a-482e-436c-bb57-36dd82d6b0cd.png">

다음과 같은 json 형식으로 받아볼 수 있습니다.
```
{'rows': [{'header': True,
   'cells': ['Machine type',
    'Virtual CPUs',
    'Memory',
    'Price (USD)',
    'Spot price* (USD)']},
  {'cells': ['c3-standard-4',
    '4',
    '16',
    {'priceByRegion': {'uscentral1': '0.20888',
      'europewest4': '0.229872',
      'useast4': '0.235144'},
     'decimalPlaces': 6},
    {'priceByRegion': {'uscentral1': '0.018952',
      'europewest4': '0.023212',
      'useast4': '0.054056'},
     'decimalPlaces': 6}]},
  {'cells': ['c3-standard-8',
    '8',
    '32',
    {'priceByRegion': {'uscentral1': '0.41776',
      'europewest4': '0.459744',
      'useast4': '0.470288'},
     'decimalPlaces': 6},
    {'priceByRegion': {'uscentral1': '0.037904',
      'europewest4': '0.046424',
      'useast4': '0.108112'},
     'decimalPlaces': 6}]},
  {'cells': ['c3-standard-22',
    '22',
    '88',
    {'priceByRegion': {'uscentral1': '1.14884',
      'europewest4': '1.264296',
      'useast4': '1.293292'},
     'decimalPlaces': 6},
    {'priceByRegion': {'uscentral1': '0.104236',
      'europewest4': '0.127666',
      'useast4': '0.297308'},
     'decimalPlaces': 6}]},
  {'cells': ['c3-standard-44',
    '44',
    '176',
    {'priceByRegion': {'uscentral1': '2.29768',
      'europewest4': '2.528592',
      'useast4': '2.586584'},
     'decimalPlaces': 6},
    {'priceByRegion': {'uscentral1': '0.208472',
      'europewest4': '0.255332',
      'useast4': '0.594616'},
     'decimalPlaces': 6}]},
  {'cells': ['c3-standard-88',
    '88',
    '352',
    {'priceByRegion': {'uscentral1': '4.59536',
      'europewest4': '5.057184',
      'useast4': '5.173168'},
     'decimalPlaces': 6},
    {'priceByRegion': {'uscentral1': '0.416944',
      'europewest4': '0.510664',
      'useast4': '1.189232'},
     'decimalPlaces': 6}]},
  {'cells': ['c3-standard-176',
    '176',
    '704',
    {'priceByRegion': {'uscentral1': '9.19072',
      'europewest4': '10.114368',
      'useast4': '10.346336'},
     'decimalPlaces': 6},
    {'priceByRegion': {'uscentral1': '0.833888',
      'europewest4': '1.021328',
      'useast4': '2.378464'},
     'decimalPlaces': 6}]}]}
```

"header" 값이 True 인 "cells"의 리스트값을 컬럼명으로 사용하여 datafame을 구성하려고하는데,
각 테이블의 컬럼 구성이나 순서가 무작위로 다른 패턴을 보여서 일괄적인 parsing 이 어려운 상황입니다.
(어떤 인스턴스 계열의 테이블은 1Y / 3Y commitment price 도 존재하고, price 정책의 순서나 네이밍이 통일되지 않은상황입니다)

그외에도, 기존에 사용하던 region naming format 이 달라졌습니다. (기존 : "us-central1" -> 현재 : "uscentral1")

위 두가지 사항 고려해서 수집 모듈 수정 작업 마무리를 진행하고 있습니다.

**Comment by kmu-leeky** [comment]
오케이. 현영아 잘 파악했네. "동적 크롤링 과정이 필요가없어지면서 시간은 매우 단축" 이 부분은 이전과 어떻게 달라진거야? 이전에는 url 리스트를 받아와서 각 url 을 일일이 crawling 해야 했던것 같은데, 그게 필요가 없다는 이야기 인건가?
그리고 header 값이 True 인것들은 실제 값이 아니라 각 컬럼의 이름을 저장하는것 같은데, 해당 값들이 약간씩 다른가보네. 그렇다면 각 리스트별로 우리가 필요로 하는 컬럼의 인덱스를 파악해서 특정 값만 얻어오게 할 필요는 있겠구나. region naming 은 이전이 더 가독성이 좋은것 같은데. aws 와 azure 의 포맷과 비교해서 어떻게 쓸런지 결정을 해보자.

**Comment by wynter122** [comment]
1. 동적 크롤링 과정이 없어지면서 시간이 단축된 부분은 말씀하신 내용이 맞습니다. iframe 의 url 별로 requests 를 모두 보내야했는데, 한번의 requests 요청만으로 크롤링 가능하게 바뀌었습니다.

2. 컬럼의 명칭이 테이블마다 비슷하긴 하지만 예외가 존재해서 부분적으로 하드코딩이 필요할 것 같습니다. 그 부분을 최소화 할 수 있게 고민중에 있습니다.

3. region 의 naming에서 - 가 빠져서 이부분을 잘 처리해야할 듯 합니다. 무엇보다 GCP의 pricelist 리소스에서는 us-central1 이렇게 제공하기때문에 저희 수집모듈에서 사용하던 명칭을 그대로 유지할 수 있으면 좋을 것 같다고 생각합니다.

**Comment by wynter122** [comment]
### 회의 결과
VM instace pricing 페이지에서는 pricing 정보를 수집하지 않고 인스턴스 타입 별 지원 region 데이터만 취하는것으로 결정되었습니다.

pricelist json 파일에서 얻은 pricing data + vm instance pricing 페이지에서 얻은 지원하는 region data
두가지로 latest.json 을 구성하도록 진행합니다.

최종적으로, 현재 GCP가 두개의 source에서 price 데이터를 제공하고 있는데, 이번 작업으로 **price 에 대해서는 pricelist.json의 데이터 소스만 제공**하는것으로 변경될예정입니다.

**Comment by kmu-leeky** [comment]
응 현영아 잘 정리했다. 이에 따른 frontend UI 변경과 저장 데이터 포맷에 대한 이슈도 별도로 생성을 해서 트래킹을 하자.

**Comment by wynter122** [comment]
### 진행상황 공유
#419 에서 데이터 수집 포맷이 크게 바뀌어 tsdb에 그간 데이터의 포맷을 변경해 다시 write 하는 작업을 진행중에 있습니다.

작업을 진행중인 노트북 입니다.
http://203.246.113.16:8800/notebooks/Hyeonyoung/tsdb_rewrite/Untitled.ipynb?kernel_name=python3

지금까지 수집된 데이터는 s3의 rawdata 를 sync 한 뒤,
VM instance pricing 값을 보고 조건부로 OnDemand Price 와 Preemptible Price 컬럼을 추가합니다.
다시 만들어진 dataframe 을 tsdb에 병렬로 write 할 예정입니다.

다만, 현재 해당 이슈를 진행하는 이유가 "VM 인스턴스 가격이 수집되지 않아서" 이고, 
이에 따라 어느 시점부터는 모든 데이터의 VM 인스턴스 가격이 -1 일것입니다. 
system-monitoring 채널을 확인해 본 결과 2023년 1월 16일 06시부터 수집이 정상적으로 되지 않은것으로 파악됩니다.

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/72314987/229739661-8a1ed8fc-7292-4d12-88b8-82ebbf272a2c.png">

이 시점부터는 따로 저장된 데이터가 없다고 판단하였고,
1월 16일 05시의 vm 인스턴스 수집 데이터를 기반으로 조건부 컬럼을 추가하여 write 하도록 하겠습니다.

write 가 모두 진행 된 이후부터는 수정된 모듈을 반영하도록 하겠습니다.

**Comment by kmu-leeky** [comment]
응 현영아 괜찮아 보인다. "VM instance pricing 값을 보고 조건부로 OnDemand Price 와 Preemptible Price 컬럼을 추가합니다." 이 이야기는 만약에 vm instance pricing 이  아예 없는 인스턴스는  아예 추가를 하지 않는다는 이야기가 맞는거지? 1월 16일 기준 이전 데이터를 사용해서 그 이후 유실된 데이터 처리하는것 좋아보인다.

**Comment by wynter122** [comment]
네 교수님. 이해하시는 내용이 맞습니다.
어제 테스트로 tsdb 에 write 해 보았고 정상적으로 잘 쓰여지는것을 확인했습니다. 아래와 같이 write 됩니다.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/72314987/230013059-add5a608-0259-4646-a9f4-39dfef3a3310.png">

실제 spotlake - gcp table 에 쓰려고 하는데, 이 작업 동안은 lambda 상의 gcp 수집 모듈에서 rawdata 만 수집하고 upload_timestream 부분은 주석처리 해두겠습니다.
작업이 끝나면 수집된 모듈을 lambda 에 반영하여 write 를 재개하면 될것같습니다.

**Comment by kmu-leeky** [comment]
오케이. 지금까지 다운로드한 raw 데이터로 변형 후 업로드를 우선 마무리 짓고 해당 업로드 사이에 발생하는 데이터는 RAW 데이터로 따로 가지고 있다가 한번에 업로드 한다는 이야기인거지? 그렇게 해도 괜찮을듯 하다.

**Comment by wynter122** [comment]
수정된 모듈 반영과
한국시간 기준 4월 12일 17시에 수집된 데이터까지의 포맷 변경 성공적으로 완료했습니다.
변경된 수집 모듈도 정상적으로 작동합니다.
