### ISSUE TITLE
GCP Preemptible VM 명칭 변경 제안

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#420]
현재 SpotLake 홈페이지에서는 GCP의 spot instance를 preemptible으로 표기하여 제공중입니다.
<img width="1585" alt="image" src="https://user-images.githubusercontent.com/66048830/230261911-947a76c8-c7f8-4e55-b85a-5d4ac6a3690a.png">

하지만 공식 document를 살펴보면 preemptible vm은 제공 중단되었으며 spot vm이라는 새로운 이름으로 제공중입니다.
<img width="242" alt="image" src="https://user-images.githubusercontent.com/66048830/230261833-e20422dc-0ffa-40d5-b830-56e89f0aa33e.png">

calculator에서는 spot과 preemptible을 병행 사용중입니다.
<img width="679" alt="image" src="https://user-images.githubusercontent.com/66048830/230262616-a1300ee4-2b30-4f2f-bd6f-ac2a2d5fc067.png">

가격 제공 페이지에서도 Spot price를 사용하고 있습니다.
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/66048830/230262839-6fcc6555-219d-4ef3-96d7-b8f2a6dbbbe2.png">

preemptible이라는 이름을 계속 사용하면 지원 중단된 서비스와 혼동될 가능성이 있을 듯 하기 때문에 Timestream column name을 바꾸지는 못하더라도, 프론트엔드에서 column의 이름을 Spot Price로 변경하는 것은 어떨까 합니다.

**Comment by kmu-leeky** [comment]
응 재일아 좋은 의견.이번 기회에 데이터베이스 업데이트 하는 김에 컬럼이름도 spot price 로 바꾸는게 좋겠다.

**Comment by wynter122** [comment]
좋은 생각입니다.
DB에 다시 쓰는 작업이 그리 오래 걸리지 않아서, 모듈 수정 완료하면 그때 컬럼명 변경해서 다시 write 작업 하겠습니다.

**Comment by wynter122** [comment]
tsdb 에 spot price 로 바꾸는것은 간단한데,
s3에 저장되는 rawdata 의 경우에도 변경이 필요할까요?
rawdata의 경우 지금까지 모아온 데이터를 변경하는것이 어려워서 이부분 처리를 어떻게 해야 적절할지 궁금합니다.

**Comment by chris0765** [comment]
사실상 가장 중요한건 유저들에게 보이는 프론트에서의 표기라서, tsdb나 rawdata의 변경이 필수는 아닙니다.
rawdata 변경이 어려우면 건너뛰어도 될 듯 합니다.

**Comment by red0sena** [comment]
현재 rawdata를 다시 전처리할 필요는 있어 보입니다. 
추후 rawdata를 가지고 다양한 분석을 할 텐데 현재 rawdata는 column순서 이름, nan값 , 유실된 데이터 등 전처리하기 까다로워 
장기적으로 보면 전처리를 다시하면서 컬럼명 변경이 필요해 보입니다. 이 문제는 추후 다른 이슈에서 다루는게 좋을 것 같습니다.

**Comment by wynter122** [comment]
그동안 모은 s3 의 전체 데이터를 다시 전처리하는것은 지금 진행하기에는 어려운 것 같습니다.
경환님 말씀대로 필요하다면 추후 rawdata 포맷 변경하는 이슈를 진행하는게 좋을 것 같습니다.

우선, 수집모듈상에서 s3에 latest 및 rawdata를 저장할 때 컬럼명을 'Spot Price' 로 변경하여 
첫 수집 ~ 수집모듈 변경 이전 까지의 데이터만 따로 전처리하여 다시 저장하도록 하겠습니다.

**Comment by kmu-leeky** [comment]
과거의 raw 데이터도 결국에는 변경을 하기는 해야겠다. 사용시에 전처리 할게 너무 많아서 불편하기는 한것 같아.
포맷을 어떻게 할런지는 조금 더 고민이 필요할것 같기는 해. 지속적으로 포맷이 변할수 있는데 그때마다 새롭게 rewrite 를 하기는 어려울테니.
raw 데이터 새로 작성하는건은 조금 더 장기적인 관점에서 활용 가능한 방향으로 작업하도록 따로 이슈를 만들어서 작업해보자. 
우선 gcp raw 데이터 재처리로 해서 이슈를 하나 만들자.
또다른 이슈로 aws, azure, gcp 모두 공용으로 사용할 포맷 등이 필요해 보이기는 한다. 그것도 별도의 이슈로 만들어서 작업해보자.

**Comment by kmu-leeky** [comment]
현영아. 그런데 "첫 수집 ~ 수집모듈 변경 이전 까지의 데이터만 따로 전처리하여 다시 저장하도록 하겠습니다." 이건 어떤 내용인거야? 첫수집 이라는게 제일 처음 gcp 수집한걸 이야기 하는거야? 그렇다면 전체 raw 데이터 재작성을 지금 작업한다는 이야기?

**Comment by wynter122** [comment]
아 그부분은 rawdata가 아니라 tsdb를 말씀드렸습니다. 본 이슈 만들어지기 전에 vm 인스턴스 컬럼을 드롭한 ondemand price, preemptible price 로 이미 write 된 상태여서 해당 작업을 지우고 preemptible -> spot 으로 변경하여 다시 tsdb에 쓰는 작업을 하겠다고 말씀드린겁니다.
또한 해장 부분은 이미 작업이 끝났습니다

**Comment by wynter122** [comment]
아 그부분은 코멘트 작성하다가 중간에 내용이 빠진 것 같습니다.

우선, 수집모듈상에서 s3에 latest 및 rawdata를 저장할 때 컬럼명을 'Spot Price' 로 변경하여
-> 앞으로 저장되는 데이터들의 컬럼명을 변경하고,

첫 수집 ~ 수집모듈 변경 이전 까지의 데이터만 따로 전처리하여 다시 저장하도록 하겠습니다
-> 이부분은 나중에 작업해도 되니 (rawdata) 추후 이슈 만들어서 진행

을 말씀드리고 싶었습니다!

**Comment by kmu-leeky** [comment]
ok. clear!

**Comment by wynter122** [comment]
수집 모듈 및, #422 에서 기존 데이터 네이밍 변경까지 완료했습니다.
