### ISSUE TITLE
GCP 컬럼명 변경에 따른 rawdata 재가공

### ISSUE THREAD

**Issue by wynter122** [ddps-lab/spotlake#422]
#412 #420 에서 진행된 작업에서 Preemptible -> Spot 으로 네이밍이 변경되었습니다.
추후 데이터 분석시 전처리를 용이하게 하기 위해 #412 이 반영되기 이전까지의 rawdata 의 데이터프레임을 재가공하여 다시 저장하는 이슈입니다.

**Comment by wynter122** [comment]
### spotlake 버킷의 gcp rawdata 재가공 하여 저장 완료

2022년 9월부터 2023년 4월 14일 23시까지의 수집분에 대한 재가공 및 저장이 완료되었습니다.

- 2023/01/16 06시 ~ 2023/04/12 07시 : VM 인스턴스 수집 누락. 바로 이전 시점의 available region 으로 처리
- 처음 ~ 2023/04/14 23시 : Savings 없음. Savings 컬럼 추가
- '-1' 행 drop
- Preemptible -> Spot 으로 이름 변경

위 사항을 변경하여 다시 저장했습니다.

기존 원본 파일은 혹시 모를 사태를 대비하여 spotlake 버킷의 gcp-old-rawdata 라는 디레토리 아래에 복사해 둔 상태이며,
현재 spotlake/rawdata/gcp 디렉토리에는 변경된 데이터 프레임들을 저장해두었습니다.

작업은 아래 링크에서 진행했습니다.
http://203.246.113.16:8800/tree/Hyeonyoung/rename_rawdata

**Comment by kmu-leeky** [comment]
오케이 현영아 잘했다. 그런데 2023/01/16 06시 ~ 2023/04/12 07시 이 기간에는 어떤 이유로 데이터 유실이 있었어? 기억이...

**Comment by wynter122** [comment]
#412 에서 진행했던 VM instance page html 포맷 변경문제였습니다!
4/12일 07시는 새로운 수집 모듈 반영 직전 시점입니다.

**Comment by kmu-leeky** [comment]
현영아. 현재 저장된 모든 GCP raw dataset 은 새로운 포맷으로 저장되어 있고, 그대로 외부에 공개되어도 큰 이슈 없겠지?

**Comment by wynter122** [comment]
넵 전체적으로 처리를 완료햐서 이슈 없을 것같습니다.
