### ISSUE TITLE
SpotLake GCP 데이터 보이지 않는 문제

### ISSUE THREAD

**Issue by chris0765** [ddps-lab/spotlake#424]
<img width="1270" alt="스크린샷 2023-04-14 오후 4 20 48" src="https://user-images.githubusercontent.com/66048830/231972902-2ebef710-cf91-4745-a0c1-91c69b2f8176.png">

Ondemand와 Spot Price 전부 NA값이 보여지고있습니다.

현재는 SpotLake에서만 확인한 상태로,

Latest 파일에만 문제가 있는 것인지, DB 데이터에 업로드가 되지 않고 있는 것이지 등의 정확한 원인을 파악 후 다시 코멘트 하겠습니다.

**Comment by red0sena** [comment]
rawdata, latest에 price가 정상적으로 들어있음을 확인하여 프론트 문제인 것으로 예상됩니다.


<img width="867" alt="Screenshot 2023-04-14 at 4 28 05 PM" src="https://user-images.githubusercontent.com/106056971/231973933-0f4df231-9b0d-45e4-992e-2ab363601208.png">



<img width="311" alt="Screenshot 2023-04-14 at 4 23 47 PM" src="https://user-images.githubusercontent.com/106056971/231973868-5c55e255-89ea-439a-8c0b-59224b138f61.png">


@wynter122 @j-myeong 확인 부탁드립니다.

**Comment by j-myeong** [comment]
@chris0765 @red0sena @wynter122 

기존 GCP Column명에서 새롭게 변경 됨에 따라 발생한 문제로 파악됩니다. 프론트엔드에 적용할 Column 변경 값을 알려주시면 빠르게 반영하도록 하겠습니다.

**Comment by wynter122** [comment]
1. VM Instance, Caculator 로 구성된 2단 컬럼이 사라집니다.
2. OnDemand Price, Spot Price, Savings 로 제공할 예정입니다.

**Comment by j-myeong** [comment]
현재 사이트에서 정상적으로 출력됨을 확인하였습니다!

<img width="1360" alt="스크린샷 2023-04-14 오후 5 28 29" src="https://user-images.githubusercontent.com/50445943/231989071-0c2fd541-5a30-45c7-9d10-f2b771b73237.png">

**Comment by wynter122** [comment]
이부분 관련하여 수집 모듈에서 수정할 사항이 있습니다.

rawdata 에서만 저장하던 savings 값이 latest 에서 빠지지 않고 전달되괴 있습니다.
latest 구성 코드가 수정되면서 빠뜨린 것 같습니다.

데이터 서빙에 문제는 없지만, 다른 벤더와 통일하기 위해 코드 수정하여 PR 올리도록 하겠습니다.
간단하게 한 줄 추가하면 되어서, 따로 이슈는 생성하지 않으려고 합니다..!

**Comment by wynter122** [comment]
수집 모듈에서 rawdata의 savings 추가완료되었고, 이와 관련하여 프론트 작업도 마무리되어 issue 클로즈합니다.
