### ISSUE TITLE
filter 부분에서 AZ 선택이 잘못됨

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#429]
현재 페이지에서 필터에서 AZ 선택시 값으로 만 선택하게 되어 있는데, AZ 값은 region code 를 포함하고 있어서 선택이 불가능함.
수정 필요

문제화면. Filters 선택 후 화면
<img width="593" alt="image" src="https://github.com/ddps-lab/spotlake/assets/17699616/0adf3815-7dcb-487f-887f-29824c89eef4">

실제 AZ 값
<img width="537" alt="image" src="https://github.com/ddps-lab/spotlake/assets/17699616/7a3b52f2-1a80-440c-b3fb-ce07e51d949f">

**Comment by j-myeong** [comment]
넵, 확인하였습니다. 필터부분에서의 type 설정이 잘못되어 있어 발생하였고 수정조치 하였습니다.
아래는 로컬 테스트 화면이며 정상적으로 작동하였습니다.

<img width="581" alt="스크린샷 2023-06-02 오후 8 51 54" src="https://github.com/ddps-lab/spotlake/assets/50445943/f41d05b4-1435-4a42-b8e8-506353511f6b">
