### ISSUE TITLE
query 시 특정 필드를 선택하지 않으면 network error 가 보임

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#438]
이전에 우리가 작업을 하면서 에러 메시지를 구체화 하게끔 한것 같은데
지금 쿼리시에 AZ 를 특정하지 않으면 network error 라는 배너가 뜸. 확인 필요.

<img width="1065" alt="image" src="https://github.com/ddps-lab/spotlake/assets/17699616/5efd07fe-daa8-437e-b091-c4de75fa6fe5">

**Comment by j-myeong** [comment]
AWS 및 Azure 벤더의 경우에는 공통적인 쿼리 외의 각각 AZ, Tier 필드가 있으나 비어있을 시, 정상적으로 체크가 되지 않았던 것 같습니다.
각 벤더의 경우에는 예외적인 조건을 적용하도록 프론트엔드 코드를 수정하였습니다.

<img width="1007" alt="스크린샷 2023-07-12 오후 8 46 48" src="https://github.com/ddps-lab/spotlake/assets/50445943/1de3ec2e-c4cc-4685-b7c2-f3c2cdee88f3">
