### ISSUE TITLE
spotlake query 에서 date 를 기봅 옵션으로 선택하게끔 해주기

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spotlake#440]
쿼리를 시험삼아 해보고 싶은 경우 날자 선택이 꽤나 번거로움.
기본은 시작날자는 현재날자 하루 전날로 종료 날자는 현재 날자로 기본으로 지정하게 해주면 좋을듯 함.

**Comment by j-myeong** [comment]
넵. 말씀해주신 내용 반영하여 시작 날짜는 오늘 기준 하루 전날, 종료 날짜는 오늘이 기본이 되도록 하였습니다.

아래는 테스트 화면이며 벤더 이동 시에는 자동으로 기본 날짜(하루 전 ~ 오늘)로 초기화됩니다.
<img width="578" alt="스크린샷 2023-07-13 오후 3 32 45" src="https://github.com/ddps-lab/spotlake/assets/50445943/419da87a-f411-461a-bc06-727d749a591e">
