### ISSUE TITLE
새로운 association.json 필요

### ISSUE THREAD

**Issue by red0sena** [ddps-lab/spotlake#442]
새로운 인스턴스가 많이 업데이트 되었지만 association.json이 업데이트 되지 않아 쿼리박스에 나타나지 않고 있습니다.
새롭게 association.json을 업데이트하는 이슈입니다.

**Comment by kmu-leeky** [comment]
기억해보니 association.json 이 업데이트 되면 자동으로 반영이 되었던것 같기는 하다. @j-myeong  한번 확인해줄래요? 만약에 그렇다면 @red0sena  이가 새로운 association,json 파일이 생성되도록 작업해 볼 수 있을까? 다른 사람이 적절할것 같다면 편하게 알려주고.

**Comment by red0sena** [comment]
[new_association.zip](https://github.com/ddps-lab/spotlake/files/12271287/new_association.zip)
@j-myeong 최신데이터로 각 벤더 association.json 파일을업데이트 하였습니다 반영 부탁드립니다.

그리고 추후에 association.json 파일 업데이트를 자동화할 필요가 있어 보입니다.

**Comment by j-myeong** [comment]
현재 코드 상으로 GCP를 제외한 벤더 (AWS, AZURE) 의 경우에는 #137 에서 제공해주셨던 URL을 활용하여 json 파일을 서버에서 받아오고 화면에 렌더링하도록 작성하였습니다.

현재 웹사이트에서는 정상적으로 서버에서 json을 받아오고 있고, 보내주신 association.json 파일과 내용이 달라 적용되지 않은 것 같습니다. 확인해주시면 감사하겠습니다. 

GCP의 경우에도 서버에서 보내주신 경우, 기존 벤더들 처럼 적용이 가능할 것 같습니다.

**Comment by red0sena** [comment]
해당이슈는 #137에서 @chris0765 이 담당한 이슈로 GCP 작업 부탁드립니다.

**Comment by red0sena** [comment]
GCP도 s3에 association.json 업로드 작업이 완료되었습니다. 
아래 URL을 select box에 GCP에 사용해 주시면 될 것 같습니다!

https://spotlake.s3.us-west-2.amazonaws.com/query-selector/associated/association_gcp.json

**Comment by red0sena** [comment]
@j-myeong for tracking

**Comment by j-myeong** [comment]
@red0sena @chris0765 

GCP는 코드상으로 적용하였고 로컬 테스트 또한 완료하였습니다!

다만, 적용하면서 확인이 필요한 사항이 하나 있었는데 전에 올려주신 new_association.zip 파일에서 AWS 파일 형식이 기존 서버에서 받아오던 형식과 달라져서 new_association 파일에 맞춰서 진행하게 될 경우에는 프론트엔드에서 코드 수정이 필요할 것 같습니다. 

둘 중 어떤 형식으로 진행하면 될 지 정해주시면 감사하겠습니다!

기존 파일 (AWS)
`
[{"a1.2xlarge": {"Region": [], "AZ": [] } ...
`

new_asso (AWS)
`
[{"ap-south-1": { "InstanceType": [], "AZ": [] } ...
`

**Comment by red0sena** [comment]
new_association.zip은 무시해주시고 AWS, Azure는 https://github.com/ddps-lab/spotlake/issues/137#issuecomment-1457977643 에서 진행했던 기존 파일 그대로 하면 될 것 같습니다!

**Comment by red0sena** [comment]
https://github.com/ddps-lab/spotlake/pull/445 에서 완료 되었으므로 close하겠습니다.
