### ISSUE TITLE
Azure Collector 수집 이슈

### ISSUE THREAD

**Issue by red0sena** [ddps-lab/spotlake#450]
Azure Collector에서 Price데이터가 정상적으로 수집되지 않고 있습니다.

수집 데이터 중복과 429에러가 발생하여 그 원인이 멀티쓰레딩에 있는것으로 예상되어 https://github.com/ddps-lab/spotlake/pull/449
에서 쓰레드락과 한번에 너무 많은 API 요청을 보내지 않도록 요청 전 0~5초 정도 sleep하는 코드를 추가하였으나 로컬에서는 잘 작동하나 람다에서는 여전히 동일한 이슈가 발생하였습니다.

람다에서 작동하지 않는 원인파악 후 PR진행하도록 하겠습니다.

**Comment by red0sena** [comment]
람다에서 작동하지 않았던 원인을 파악하여 수정하였습니다.

Azure Price 데이터는  아래와 같이 REST API를 이용하여 API를 가져오는데
```
    get_link = "https://prices.azure.com:443/api/ ...... &$skip=" + str(skip_num)
    response = requests.get(get_link)
```
한번 API요청에 모든 응답이 오지 않고 skip_num을 달리하며 멀티쓰레딩을 하여 모든 Price 데이터를 가져왔습니다.

기존에는 skip_num이 100 단위로 100, 200, 300 ... 이런식으로 한번에 100개 데이터의 응답이 와 100단위로 skip_num을 달리하며 응답을 모두 모았는데 

최근에 응답이 100개 단위가 아닌 1000개단위로 변경되어 100개 단위의 응답을 얻는 기존의 코드로는 엄청난 데이터 중복이 발생하여

메모리가 널널한 로컬에서는 이 응답을 중복을 모두 처리할 수 있었지만 람다에서는 작동하지 않은 것으로 파악되었습니다. 

이에 코드를 수정하였고 데이터가 람다에서도 정상적으로 수집됨을 확인하였습니다.

테스트로 내일까지 지켜보고 이상 없을 시 코드 PR하도록 하겠습니다.

**Comment by kmu-leeky** [comment]
오. 그러면 이제 요청을 보내는 갯수가 많이 줄어들것 같네? 잘 발견해서 디버깅했다.

**Comment by red0sena** [comment]
네 한번의 API 요청 응답 데이터 개수가 100개에서 1000개로 늘어나 1/10으로 줄었습니다. #449 에 수정사항 PR 하였습니다.

**Comment by red0sena** [comment]
원인을 파악하여 코드를 수정하였고 데이터가 정상 수집됨을 확인하였으므로 close하겠습니다.
