### ISSUE TITLE
손실된 Azure rawdata 복구

### ISSUE THREAD

**Issue by red0sena** [ddps-lab/spotlake#451]
Azure rawdata가 2023/09/14 23:00 부터 지금까지 Collector 이슈로 제대로 수집되지 않았습니다.
그러나 IF는 바로 따로 수집하였고 Price는 매달 1일에 1번만 변화하므로
유실된 9월, 10월 Price 데이터는 해당 달에 해당하는 데이터로 모두 채우고, 따로 수집한 IF를 merge하여 손실된 rawdata를 복구하도록 하겠습니다.

**Comment by kmu-leeky** [comment]
경환아 이건 일부 데이터가 유실된거지? 그 기간 전체 데이터가 없는건 아닌거지? Azure 수집 건수가 변화가 있더니 그 영향인것 같기도 하네.

**Comment by red0sena** [comment]
네 전체데이터 유실은 아닌 일부 Price데이터와 IF데이터는 남아 있었습니다.

**Comment by red0sena** [comment]
<img width="1807" alt="image" src="https://github.com/ddps-lab/spotlake/assets/106056971/39b50ed9-df31-49e5-b598-ad1244482b77">

유실된 데이터들을 모두 복구 완료하였습니다. 이 이슈는 close하겠습니다.

**Comment by kmu-leeky** [comment]
경환아 데이터 복구는 어떻게 한거야? 그냥 데이터만 변하지 않았다고 가정하고 raw 데이터에 추가해둔건가?

**Comment by red0sena** [comment]
네 지금까지 Azure Price데이터는 매달 1일 일괄적으로 변화했기 때문에 
2023/09/14 23:00 ~ 2023/10/17 17:00
위 데이터 유실 기간 중 9월은 9월 13일 00:00데이터의 Price데이터를 이용하고 10월 데이터는 10월 18일 03:00의 Price데이터를 이용하여 모두 채우고 
매일 변화하는 IF같은 경우는 유실을 방지하기 위해 따로 수집하였기 때문에 해당 시간에 맞는 IF로 merge하여 데이터를 복구하였습니다.
