### ISSUE TITLE
Sandevistan 사이트 작업 초안

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/spotlake#484]
현재 Sandecistan 사이트 작업의 초안 공유해드립니다.

![image](https://github.com/user-attachments/assets/93774975-1150-4c1c-b028-b2dc9ebfbbae)

색깔은 임의로 지정했으며, Sandevistan 쿼리에 필요한 사용자 지정 Instance와 Region, 확인할 Start Date 및 End Date 기간, Weight(소수 1째자리까지만 입력)를 받도록 하였습니다.
혹시 추후에 다른 서비스에서도 추가될 수도 있어서 AWS를 선택하여 진행하도록 진행하였습니다.

추가되어야 할 부분이나 수정되어야 할 부분이 있다면 반영할 예정이며, 앞으로 세부적으로 컬러나 열 이름 등을 지정해야 합니다.

**Comment by Kim-Yul** [comment]
추가되면 좋을 것 같은 사항

1. Weight 값에 수정이 필요해보입니다. 현재 0~1까지 소수 첫번째 자리까지만 받도록 되어 있는데, 어디가 0이고 어디가 1인지 알 수 없습니다. 그리고 포인터를 가져다 대면 1이 안정성 우선, 0이 비용 우선이라는 등의 언급이 필요해보입니다.

2. 테마 색을 바꿀 필요가 있어보입니다.

3. Spotlake로 이동할 버튼이 생길 위치가 잡혀있으면 좋을 것 같습니다.

**Comment by kmu-leeky** [comment]
instance 및 region 은 지금 보이는건 하나만 select 가능한것 아닌가? 여러개의 타입과 region 이 선택가능해야해. All 도 가능해야 하고.
저기서 날자를 지정하는 목적은 뭐야?

**Comment by Kim-Yul** [comment]
현재 instance 및 region 는 하나만 select 가능한 것 맞습니다. 체크를 못했던 부분이라 여러 개 선택 가능하도록 수정하겠습니다.
예전에 미팅을 진행했을 때 3일로 지정해두기로 하였으나 사용자로부터 과거 며칠의 데이터를 확인할 것인지 사용자에게 선택을 준다고 하셨기에 그 부분을 반영하려고 했던 것입니다. 그러나 현재 기준으로 며칠 전의 데이터까지 볼 것인지를 고민하는 것이기 때문에 위와 같은 형태보다는 int 타입의 숫자를 받아 1이면 1일전 데이터까지 고려하는 식으로 수정해야 할 것 같습니다.

**Comment by kmu-leeky** [comment]
응 유림아. 이야기한대로 하는게 좋을것 같아. 특정 시점의 데이터를 지정해주는 것도 좋을것 같기는 한데 (캘린더 이용해서), 조금 더 편한 방법은 그냥 과거 특정 일수의 데이터를 사용하는게 나을것 같긴 하다. calender 가 있으니, 해당 기능도 두고, 그냥 이전 특정 일수 선택하는 옵션 2개를 다 지원 할수도 있을까?

**Comment by Kim-Yul** [comment]
지원할 수 있을 것 같습니다.
과거 특정 일수의 데이터 입력이 들어오면 캘린더 입력 값을 제거하고, 캘린더를 지정하면 특정 일수의 데이터 입력 값을 제거하는 식으로 하여 문제 없이 지원할 수 있을 것으로 생각됩니다.
캘린더는 현재 시점이 아니더라도 특정 시점을 검색해볼 수 있도록 현재처럼 놔두고, 새로 특정 일수 데이터 입력 칸을 추가하여 상호작용 하도록 수정 진행하겠습니다.
혹시 더 챙겨봐야하는 점이 있다면 전달 부탁드립니다. 추가로 Sandevistan 테마 색으로 원하시는 컬러가 있으시면 안내 부탁드립니다.

**Comment by kmu-leeky** [comment]
다른건 괜찮아보인다. 만들어서 백엔드 API 와 연결해보자. 12월 초에 논문 리뷰가 공개되면 빠르게 활용해야 할수도 있을것 같아.

**Comment by Kim-Yul** [comment]
frontend github 경로

기존 : frontend/build/
변경 : frontend/spotlake/build/
         frontend/sandevistan/build/

CI/CD 될 수 있도록 sync.yaml 도 각각 수정 및 추가합니다.
aws 내에 정적 웹 사이트가 올라갈 수 있도록 kmuddps 계정에 s3 버킷 및 cloudfront를 생성해둡니다.

sandevistan 의 경우 도메인이 퍼블릭하게 공개되지 않도록 추후 결정이 필요합니다.

**Comment by Kim-Yul** [comment]
해당 작업은 새로 만든 repo에서 이어서 진행하도록 하겠습니다.
